package com.fucai.dao;

import com.fucai.model.BasePeriod;
import com.fucai.model.BasePeriodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasePeriodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    int countByExample(BasePeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    int deleteByExample(BasePeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer periodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    int insert(BasePeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    int insertSelective(BasePeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    List<BasePeriod> selectByExample(BasePeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    BasePeriod selectByPrimaryKey(Integer periodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BasePeriod record, @Param("example") BasePeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BasePeriod record, @Param("example") BasePeriodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BasePeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BasePeriod record);
}