package com.fucai.dao;

import com.fucai.model.FiftyRedBallProbability;
import com.fucai.model.FiftyRedBallProbabilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FiftyRedBallProbabilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_red_ball_probability
     *
     * @mbggenerated
     */
    int countByExample(FiftyRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_red_ball_probability
     *
     * @mbggenerated
     */
    int deleteByExample(FiftyRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_red_ball_probability
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_red_ball_probability
     *
     * @mbggenerated
     */
    int insert(FiftyRedBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_red_ball_probability
     *
     * @mbggenerated
     */
    int insertSelective(FiftyRedBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_red_ball_probability
     *
     * @mbggenerated
     */
    List<FiftyRedBallProbability> selectByExample(FiftyRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_red_ball_probability
     *
     * @mbggenerated
     */
    FiftyRedBallProbability selectByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FiftyRedBallProbability record, @Param("example") FiftyRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FiftyRedBallProbability record, @Param("example") FiftyRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FiftyRedBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FiftyRedBallProbability record);
}