package com.fucai.dao;

import com.fucai.model.FiftyBlueBallProbability;
import com.fucai.model.FiftyBlueBallProbabilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FiftyBlueBallProbabilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_blue_ball_probability
     *
     * @mbggenerated
     */
    int countByExample(FiftyBlueBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_blue_ball_probability
     *
     * @mbggenerated
     */
    int deleteByExample(FiftyBlueBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_blue_ball_probability
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_blue_ball_probability
     *
     * @mbggenerated
     */
    int insert(FiftyBlueBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_blue_ball_probability
     *
     * @mbggenerated
     */
    int insertSelective(FiftyBlueBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_blue_ball_probability
     *
     * @mbggenerated
     */
    List<FiftyBlueBallProbability> selectByExample(FiftyBlueBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_blue_ball_probability
     *
     * @mbggenerated
     */
    FiftyBlueBallProbability selectByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_blue_ball_probability
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FiftyBlueBallProbability record, @Param("example") FiftyBlueBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_blue_ball_probability
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FiftyBlueBallProbability record, @Param("example") FiftyBlueBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_blue_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FiftyBlueBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fifty_blue_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FiftyBlueBallProbability record);
}