package com.fucai.dao;

import com.fucai.model.FiveRedBallProbability;
import com.fucai.model.FiveRedBallProbabilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FiveRedBallProbabilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table five_red_ball_probability
     *
     * @mbggenerated
     */
    int countByExample(FiveRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table five_red_ball_probability
     *
     * @mbggenerated
     */
    int deleteByExample(FiveRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table five_red_ball_probability
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table five_red_ball_probability
     *
     * @mbggenerated
     */
    int insert(FiveRedBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table five_red_ball_probability
     *
     * @mbggenerated
     */
    int insertSelective(FiveRedBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table five_red_ball_probability
     *
     * @mbggenerated
     */
    List<FiveRedBallProbability> selectByExample(FiveRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table five_red_ball_probability
     *
     * @mbggenerated
     */
    FiveRedBallProbability selectByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table five_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FiveRedBallProbability record, @Param("example") FiveRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table five_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FiveRedBallProbability record, @Param("example") FiveRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table five_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FiveRedBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table five_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FiveRedBallProbability record);
}