package com.fucai.dao;

import com.fucai.model.OddEvenProbability;
import com.fucai.model.OddEvenProbabilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OddEvenProbabilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odd_even_probability
     *
     * @mbggenerated
     */
    int countByExample(OddEvenProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odd_even_probability
     *
     * @mbggenerated
     */
    int deleteByExample(OddEvenProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odd_even_probability
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer oddEvenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odd_even_probability
     *
     * @mbggenerated
     */
    int insert(OddEvenProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odd_even_probability
     *
     * @mbggenerated
     */
    int insertSelective(OddEvenProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odd_even_probability
     *
     * @mbggenerated
     */
    List<OddEvenProbability> selectByExample(OddEvenProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odd_even_probability
     *
     * @mbggenerated
     */
    OddEvenProbability selectByPrimaryKey(Integer oddEvenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odd_even_probability
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OddEvenProbability record, @Param("example") OddEvenProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odd_even_probability
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OddEvenProbability record, @Param("example") OddEvenProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odd_even_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OddEvenProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odd_even_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OddEvenProbability record);
}