package com.fucai.dao;

import com.fucai.model.OneHundredRedBallProbability;
import com.fucai.model.OneHundredRedBallProbabilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OneHundredRedBallProbabilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_red_ball_probability
     *
     * @mbggenerated
     */
    int countByExample(OneHundredRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_red_ball_probability
     *
     * @mbggenerated
     */
    int deleteByExample(OneHundredRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_red_ball_probability
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_red_ball_probability
     *
     * @mbggenerated
     */
    int insert(OneHundredRedBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_red_ball_probability
     *
     * @mbggenerated
     */
    int insertSelective(OneHundredRedBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_red_ball_probability
     *
     * @mbggenerated
     */
    List<OneHundredRedBallProbability> selectByExample(OneHundredRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_red_ball_probability
     *
     * @mbggenerated
     */
    OneHundredRedBallProbability selectByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OneHundredRedBallProbability record, @Param("example") OneHundredRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OneHundredRedBallProbability record, @Param("example") OneHundredRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OneHundredRedBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OneHundredRedBallProbability record);
}