package com.fucai.dao;

import com.fucai.model.OneHundredBlueBallProbability;
import com.fucai.model.OneHundredBlueBallProbabilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OneHundredBlueBallProbabilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_blue_ball_probability
     *
     * @mbggenerated
     */
    int countByExample(OneHundredBlueBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_blue_ball_probability
     *
     * @mbggenerated
     */
    int deleteByExample(OneHundredBlueBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_blue_ball_probability
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_blue_ball_probability
     *
     * @mbggenerated
     */
    int insert(OneHundredBlueBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_blue_ball_probability
     *
     * @mbggenerated
     */
    int insertSelective(OneHundredBlueBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_blue_ball_probability
     *
     * @mbggenerated
     */
    List<OneHundredBlueBallProbability> selectByExample(OneHundredBlueBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_blue_ball_probability
     *
     * @mbggenerated
     */
    OneHundredBlueBallProbability selectByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_blue_ball_probability
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OneHundredBlueBallProbability record, @Param("example") OneHundredBlueBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_blue_ball_probability
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OneHundredBlueBallProbability record, @Param("example") OneHundredBlueBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_blue_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OneHundredBlueBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table one_hundred_blue_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OneHundredBlueBallProbability record);
}