package com.fucai.dao;

import com.fucai.model.RedBallProbability;
import com.fucai.model.RedBallProbabilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RedBallProbabilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_ball_probability
     *
     * @mbggenerated
     */
    int countByExample(RedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_ball_probability
     *
     * @mbggenerated
     */
    int deleteByExample(RedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_ball_probability
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_ball_probability
     *
     * @mbggenerated
     */
    int insert(RedBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_ball_probability
     *
     * @mbggenerated
     */
    int insertSelective(RedBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_ball_probability
     *
     * @mbggenerated
     */
    List<RedBallProbability> selectByExample(RedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_ball_probability
     *
     * @mbggenerated
     */
    RedBallProbability selectByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_ball_probability
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RedBallProbability record, @Param("example") RedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_ball_probability
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RedBallProbability record, @Param("example") RedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RedBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RedBallProbability record);
}