package com.fucai.dao;

import com.fucai.model.SectionProbability;
import com.fucai.model.SectionProbabilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SectionProbabilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_probability
     *
     * @mbggenerated
     */
    int countByExample(SectionProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_probability
     *
     * @mbggenerated
     */
    int deleteByExample(SectionProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_probability
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_probability
     *
     * @mbggenerated
     */
    int insert(SectionProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_probability
     *
     * @mbggenerated
     */
    int insertSelective(SectionProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_probability
     *
     * @mbggenerated
     */
    List<SectionProbability> selectByExample(SectionProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_probability
     *
     * @mbggenerated
     */
    SectionProbability selectByPrimaryKey(Integer sectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_probability
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SectionProbability record, @Param("example") SectionProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_probability
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SectionProbability record, @Param("example") SectionProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SectionProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SectionProbability record);
}