package com.fucai.dao;

import com.fucai.model.ThirtyBlueBallProbability;
import com.fucai.model.ThirtyBlueBallProbabilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThirtyBlueBallProbabilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_blue_ball_probability
     *
     * @mbggenerated
     */
    int countByExample(ThirtyBlueBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_blue_ball_probability
     *
     * @mbggenerated
     */
    int deleteByExample(ThirtyBlueBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_blue_ball_probability
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_blue_ball_probability
     *
     * @mbggenerated
     */
    int insert(ThirtyBlueBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_blue_ball_probability
     *
     * @mbggenerated
     */
    int insertSelective(ThirtyBlueBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_blue_ball_probability
     *
     * @mbggenerated
     */
    List<ThirtyBlueBallProbability> selectByExample(ThirtyBlueBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_blue_ball_probability
     *
     * @mbggenerated
     */
    ThirtyBlueBallProbability selectByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_blue_ball_probability
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ThirtyBlueBallProbability record, @Param("example") ThirtyBlueBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_blue_ball_probability
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ThirtyBlueBallProbability record, @Param("example") ThirtyBlueBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_blue_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ThirtyBlueBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_blue_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ThirtyBlueBallProbability record);
}