package com.fucai.dao;

import com.fucai.model.ThirtyRedBallProbability;
import com.fucai.model.ThirtyRedBallProbabilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThirtyRedBallProbabilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    int countByExample(ThirtyRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    int deleteByExample(ThirtyRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    int insert(ThirtyRedBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    int insertSelective(ThirtyRedBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    List<ThirtyRedBallProbability> selectByExample(ThirtyRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    ThirtyRedBallProbability selectByPrimaryKey(Integer ballProbabilityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ThirtyRedBallProbability record, @Param("example") ThirtyRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ThirtyRedBallProbability record, @Param("example") ThirtyRedBallProbabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ThirtyRedBallProbability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ThirtyRedBallProbability record);
}