package com.fucai.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BasePeriodExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_period
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_period
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_period
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    public BasePeriodExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_period
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPeriodIdIsNull() {
            addCriterion("PERIOD_ID is null");
            return (Criteria) this;
        }

        public Criteria andPeriodIdIsNotNull() {
            addCriterion("PERIOD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodIdEqualTo(Integer value) {
            addCriterion("PERIOD_ID =", value, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdNotEqualTo(Integer value) {
            addCriterion("PERIOD_ID <>", value, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdGreaterThan(Integer value) {
            addCriterion("PERIOD_ID >", value, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PERIOD_ID >=", value, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdLessThan(Integer value) {
            addCriterion("PERIOD_ID <", value, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdLessThanOrEqualTo(Integer value) {
            addCriterion("PERIOD_ID <=", value, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdIn(List<Integer> values) {
            addCriterion("PERIOD_ID in", values, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdNotIn(List<Integer> values) {
            addCriterion("PERIOD_ID not in", values, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdBetween(Integer value1, Integer value2) {
            addCriterion("PERIOD_ID between", value1, value2, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PERIOD_ID not between", value1, value2, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodNumberIsNull() {
            addCriterion("PERIOD_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andPeriodNumberIsNotNull() {
            addCriterion("PERIOD_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodNumberEqualTo(String value) {
            addCriterion("PERIOD_NUMBER =", value, "periodNumber");
            return (Criteria) this;
        }

        public Criteria andPeriodNumberNotEqualTo(String value) {
            addCriterion("PERIOD_NUMBER <>", value, "periodNumber");
            return (Criteria) this;
        }

        public Criteria andPeriodNumberGreaterThan(String value) {
            addCriterion("PERIOD_NUMBER >", value, "periodNumber");
            return (Criteria) this;
        }

        public Criteria andPeriodNumberGreaterThanOrEqualTo(String value) {
            addCriterion("PERIOD_NUMBER >=", value, "periodNumber");
            return (Criteria) this;
        }

        public Criteria andPeriodNumberLessThan(String value) {
            addCriterion("PERIOD_NUMBER <", value, "periodNumber");
            return (Criteria) this;
        }

        public Criteria andPeriodNumberLessThanOrEqualTo(String value) {
            addCriterion("PERIOD_NUMBER <=", value, "periodNumber");
            return (Criteria) this;
        }

        public Criteria andPeriodNumberLike(String value) {
            addCriterion("PERIOD_NUMBER like", value, "periodNumber");
            return (Criteria) this;
        }

        public Criteria andPeriodNumberNotLike(String value) {
            addCriterion("PERIOD_NUMBER not like", value, "periodNumber");
            return (Criteria) this;
        }

        public Criteria andPeriodNumberIn(List<String> values) {
            addCriterion("PERIOD_NUMBER in", values, "periodNumber");
            return (Criteria) this;
        }

        public Criteria andPeriodNumberNotIn(List<String> values) {
            addCriterion("PERIOD_NUMBER not in", values, "periodNumber");
            return (Criteria) this;
        }

        public Criteria andPeriodNumberBetween(String value1, String value2) {
            addCriterion("PERIOD_NUMBER between", value1, value2, "periodNumber");
            return (Criteria) this;
        }

        public Criteria andPeriodNumberNotBetween(String value1, String value2) {
            addCriterion("PERIOD_NUMBER not between", value1, value2, "periodNumber");
            return (Criteria) this;
        }

        public Criteria andRedOneBallIsNull() {
            addCriterion("RED_ONE_BALL is null");
            return (Criteria) this;
        }

        public Criteria andRedOneBallIsNotNull() {
            addCriterion("RED_ONE_BALL is not null");
            return (Criteria) this;
        }

        public Criteria andRedOneBallEqualTo(String value) {
            addCriterion("RED_ONE_BALL =", value, "redOneBall");
            return (Criteria) this;
        }

        public Criteria andRedOneBallNotEqualTo(String value) {
            addCriterion("RED_ONE_BALL <>", value, "redOneBall");
            return (Criteria) this;
        }

        public Criteria andRedOneBallGreaterThan(String value) {
            addCriterion("RED_ONE_BALL >", value, "redOneBall");
            return (Criteria) this;
        }

        public Criteria andRedOneBallGreaterThanOrEqualTo(String value) {
            addCriterion("RED_ONE_BALL >=", value, "redOneBall");
            return (Criteria) this;
        }

        public Criteria andRedOneBallLessThan(String value) {
            addCriterion("RED_ONE_BALL <", value, "redOneBall");
            return (Criteria) this;
        }

        public Criteria andRedOneBallLessThanOrEqualTo(String value) {
            addCriterion("RED_ONE_BALL <=", value, "redOneBall");
            return (Criteria) this;
        }

        public Criteria andRedOneBallLike(String value) {
            addCriterion("RED_ONE_BALL like", value, "redOneBall");
            return (Criteria) this;
        }

        public Criteria andRedOneBallNotLike(String value) {
            addCriterion("RED_ONE_BALL not like", value, "redOneBall");
            return (Criteria) this;
        }

        public Criteria andRedOneBallIn(List<String> values) {
            addCriterion("RED_ONE_BALL in", values, "redOneBall");
            return (Criteria) this;
        }

        public Criteria andRedOneBallNotIn(List<String> values) {
            addCriterion("RED_ONE_BALL not in", values, "redOneBall");
            return (Criteria) this;
        }

        public Criteria andRedOneBallBetween(String value1, String value2) {
            addCriterion("RED_ONE_BALL between", value1, value2, "redOneBall");
            return (Criteria) this;
        }

        public Criteria andRedOneBallNotBetween(String value1, String value2) {
            addCriterion("RED_ONE_BALL not between", value1, value2, "redOneBall");
            return (Criteria) this;
        }

        public Criteria andRedTwoBallIsNull() {
            addCriterion("RED_TWO_BALL is null");
            return (Criteria) this;
        }

        public Criteria andRedTwoBallIsNotNull() {
            addCriterion("RED_TWO_BALL is not null");
            return (Criteria) this;
        }

        public Criteria andRedTwoBallEqualTo(String value) {
            addCriterion("RED_TWO_BALL =", value, "redTwoBall");
            return (Criteria) this;
        }

        public Criteria andRedTwoBallNotEqualTo(String value) {
            addCriterion("RED_TWO_BALL <>", value, "redTwoBall");
            return (Criteria) this;
        }

        public Criteria andRedTwoBallGreaterThan(String value) {
            addCriterion("RED_TWO_BALL >", value, "redTwoBall");
            return (Criteria) this;
        }

        public Criteria andRedTwoBallGreaterThanOrEqualTo(String value) {
            addCriterion("RED_TWO_BALL >=", value, "redTwoBall");
            return (Criteria) this;
        }

        public Criteria andRedTwoBallLessThan(String value) {
            addCriterion("RED_TWO_BALL <", value, "redTwoBall");
            return (Criteria) this;
        }

        public Criteria andRedTwoBallLessThanOrEqualTo(String value) {
            addCriterion("RED_TWO_BALL <=", value, "redTwoBall");
            return (Criteria) this;
        }

        public Criteria andRedTwoBallLike(String value) {
            addCriterion("RED_TWO_BALL like", value, "redTwoBall");
            return (Criteria) this;
        }

        public Criteria andRedTwoBallNotLike(String value) {
            addCriterion("RED_TWO_BALL not like", value, "redTwoBall");
            return (Criteria) this;
        }

        public Criteria andRedTwoBallIn(List<String> values) {
            addCriterion("RED_TWO_BALL in", values, "redTwoBall");
            return (Criteria) this;
        }

        public Criteria andRedTwoBallNotIn(List<String> values) {
            addCriterion("RED_TWO_BALL not in", values, "redTwoBall");
            return (Criteria) this;
        }

        public Criteria andRedTwoBallBetween(String value1, String value2) {
            addCriterion("RED_TWO_BALL between", value1, value2, "redTwoBall");
            return (Criteria) this;
        }

        public Criteria andRedTwoBallNotBetween(String value1, String value2) {
            addCriterion("RED_TWO_BALL not between", value1, value2, "redTwoBall");
            return (Criteria) this;
        }

        public Criteria andRedThreeBallIsNull() {
            addCriterion("RED_THREE_BALL is null");
            return (Criteria) this;
        }

        public Criteria andRedThreeBallIsNotNull() {
            addCriterion("RED_THREE_BALL is not null");
            return (Criteria) this;
        }

        public Criteria andRedThreeBallEqualTo(String value) {
            addCriterion("RED_THREE_BALL =", value, "redThreeBall");
            return (Criteria) this;
        }

        public Criteria andRedThreeBallNotEqualTo(String value) {
            addCriterion("RED_THREE_BALL <>", value, "redThreeBall");
            return (Criteria) this;
        }

        public Criteria andRedThreeBallGreaterThan(String value) {
            addCriterion("RED_THREE_BALL >", value, "redThreeBall");
            return (Criteria) this;
        }

        public Criteria andRedThreeBallGreaterThanOrEqualTo(String value) {
            addCriterion("RED_THREE_BALL >=", value, "redThreeBall");
            return (Criteria) this;
        }

        public Criteria andRedThreeBallLessThan(String value) {
            addCriterion("RED_THREE_BALL <", value, "redThreeBall");
            return (Criteria) this;
        }

        public Criteria andRedThreeBallLessThanOrEqualTo(String value) {
            addCriterion("RED_THREE_BALL <=", value, "redThreeBall");
            return (Criteria) this;
        }

        public Criteria andRedThreeBallLike(String value) {
            addCriterion("RED_THREE_BALL like", value, "redThreeBall");
            return (Criteria) this;
        }

        public Criteria andRedThreeBallNotLike(String value) {
            addCriterion("RED_THREE_BALL not like", value, "redThreeBall");
            return (Criteria) this;
        }

        public Criteria andRedThreeBallIn(List<String> values) {
            addCriterion("RED_THREE_BALL in", values, "redThreeBall");
            return (Criteria) this;
        }

        public Criteria andRedThreeBallNotIn(List<String> values) {
            addCriterion("RED_THREE_BALL not in", values, "redThreeBall");
            return (Criteria) this;
        }

        public Criteria andRedThreeBallBetween(String value1, String value2) {
            addCriterion("RED_THREE_BALL between", value1, value2, "redThreeBall");
            return (Criteria) this;
        }

        public Criteria andRedThreeBallNotBetween(String value1, String value2) {
            addCriterion("RED_THREE_BALL not between", value1, value2, "redThreeBall");
            return (Criteria) this;
        }

        public Criteria andRedFourBallIsNull() {
            addCriterion("RED_FOUR_BALL is null");
            return (Criteria) this;
        }

        public Criteria andRedFourBallIsNotNull() {
            addCriterion("RED_FOUR_BALL is not null");
            return (Criteria) this;
        }

        public Criteria andRedFourBallEqualTo(String value) {
            addCriterion("RED_FOUR_BALL =", value, "redFourBall");
            return (Criteria) this;
        }

        public Criteria andRedFourBallNotEqualTo(String value) {
            addCriterion("RED_FOUR_BALL <>", value, "redFourBall");
            return (Criteria) this;
        }

        public Criteria andRedFourBallGreaterThan(String value) {
            addCriterion("RED_FOUR_BALL >", value, "redFourBall");
            return (Criteria) this;
        }

        public Criteria andRedFourBallGreaterThanOrEqualTo(String value) {
            addCriterion("RED_FOUR_BALL >=", value, "redFourBall");
            return (Criteria) this;
        }

        public Criteria andRedFourBallLessThan(String value) {
            addCriterion("RED_FOUR_BALL <", value, "redFourBall");
            return (Criteria) this;
        }

        public Criteria andRedFourBallLessThanOrEqualTo(String value) {
            addCriterion("RED_FOUR_BALL <=", value, "redFourBall");
            return (Criteria) this;
        }

        public Criteria andRedFourBallLike(String value) {
            addCriterion("RED_FOUR_BALL like", value, "redFourBall");
            return (Criteria) this;
        }

        public Criteria andRedFourBallNotLike(String value) {
            addCriterion("RED_FOUR_BALL not like", value, "redFourBall");
            return (Criteria) this;
        }

        public Criteria andRedFourBallIn(List<String> values) {
            addCriterion("RED_FOUR_BALL in", values, "redFourBall");
            return (Criteria) this;
        }

        public Criteria andRedFourBallNotIn(List<String> values) {
            addCriterion("RED_FOUR_BALL not in", values, "redFourBall");
            return (Criteria) this;
        }

        public Criteria andRedFourBallBetween(String value1, String value2) {
            addCriterion("RED_FOUR_BALL between", value1, value2, "redFourBall");
            return (Criteria) this;
        }

        public Criteria andRedFourBallNotBetween(String value1, String value2) {
            addCriterion("RED_FOUR_BALL not between", value1, value2, "redFourBall");
            return (Criteria) this;
        }

        public Criteria andRedFiveBallIsNull() {
            addCriterion("RED_FIVE_BALL is null");
            return (Criteria) this;
        }

        public Criteria andRedFiveBallIsNotNull() {
            addCriterion("RED_FIVE_BALL is not null");
            return (Criteria) this;
        }

        public Criteria andRedFiveBallEqualTo(String value) {
            addCriterion("RED_FIVE_BALL =", value, "redFiveBall");
            return (Criteria) this;
        }

        public Criteria andRedFiveBallNotEqualTo(String value) {
            addCriterion("RED_FIVE_BALL <>", value, "redFiveBall");
            return (Criteria) this;
        }

        public Criteria andRedFiveBallGreaterThan(String value) {
            addCriterion("RED_FIVE_BALL >", value, "redFiveBall");
            return (Criteria) this;
        }

        public Criteria andRedFiveBallGreaterThanOrEqualTo(String value) {
            addCriterion("RED_FIVE_BALL >=", value, "redFiveBall");
            return (Criteria) this;
        }

        public Criteria andRedFiveBallLessThan(String value) {
            addCriterion("RED_FIVE_BALL <", value, "redFiveBall");
            return (Criteria) this;
        }

        public Criteria andRedFiveBallLessThanOrEqualTo(String value) {
            addCriterion("RED_FIVE_BALL <=", value, "redFiveBall");
            return (Criteria) this;
        }

        public Criteria andRedFiveBallLike(String value) {
            addCriterion("RED_FIVE_BALL like", value, "redFiveBall");
            return (Criteria) this;
        }

        public Criteria andRedFiveBallNotLike(String value) {
            addCriterion("RED_FIVE_BALL not like", value, "redFiveBall");
            return (Criteria) this;
        }

        public Criteria andRedFiveBallIn(List<String> values) {
            addCriterion("RED_FIVE_BALL in", values, "redFiveBall");
            return (Criteria) this;
        }

        public Criteria andRedFiveBallNotIn(List<String> values) {
            addCriterion("RED_FIVE_BALL not in", values, "redFiveBall");
            return (Criteria) this;
        }

        public Criteria andRedFiveBallBetween(String value1, String value2) {
            addCriterion("RED_FIVE_BALL between", value1, value2, "redFiveBall");
            return (Criteria) this;
        }

        public Criteria andRedFiveBallNotBetween(String value1, String value2) {
            addCriterion("RED_FIVE_BALL not between", value1, value2, "redFiveBall");
            return (Criteria) this;
        }

        public Criteria andRedSixBallIsNull() {
            addCriterion("RED_SIX_BALL is null");
            return (Criteria) this;
        }

        public Criteria andRedSixBallIsNotNull() {
            addCriterion("RED_SIX_BALL is not null");
            return (Criteria) this;
        }

        public Criteria andRedSixBallEqualTo(String value) {
            addCriterion("RED_SIX_BALL =", value, "redSixBall");
            return (Criteria) this;
        }

        public Criteria andRedSixBallNotEqualTo(String value) {
            addCriterion("RED_SIX_BALL <>", value, "redSixBall");
            return (Criteria) this;
        }

        public Criteria andRedSixBallGreaterThan(String value) {
            addCriterion("RED_SIX_BALL >", value, "redSixBall");
            return (Criteria) this;
        }

        public Criteria andRedSixBallGreaterThanOrEqualTo(String value) {
            addCriterion("RED_SIX_BALL >=", value, "redSixBall");
            return (Criteria) this;
        }

        public Criteria andRedSixBallLessThan(String value) {
            addCriterion("RED_SIX_BALL <", value, "redSixBall");
            return (Criteria) this;
        }

        public Criteria andRedSixBallLessThanOrEqualTo(String value) {
            addCriterion("RED_SIX_BALL <=", value, "redSixBall");
            return (Criteria) this;
        }

        public Criteria andRedSixBallLike(String value) {
            addCriterion("RED_SIX_BALL like", value, "redSixBall");
            return (Criteria) this;
        }

        public Criteria andRedSixBallNotLike(String value) {
            addCriterion("RED_SIX_BALL not like", value, "redSixBall");
            return (Criteria) this;
        }

        public Criteria andRedSixBallIn(List<String> values) {
            addCriterion("RED_SIX_BALL in", values, "redSixBall");
            return (Criteria) this;
        }

        public Criteria andRedSixBallNotIn(List<String> values) {
            addCriterion("RED_SIX_BALL not in", values, "redSixBall");
            return (Criteria) this;
        }

        public Criteria andRedSixBallBetween(String value1, String value2) {
            addCriterion("RED_SIX_BALL between", value1, value2, "redSixBall");
            return (Criteria) this;
        }

        public Criteria andRedSixBallNotBetween(String value1, String value2) {
            addCriterion("RED_SIX_BALL not between", value1, value2, "redSixBall");
            return (Criteria) this;
        }

        public Criteria andBlueBallIsNull() {
            addCriterion("BLUE_BALL is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallIsNotNull() {
            addCriterion("BLUE_BALL is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallEqualTo(String value) {
            addCriterion("BLUE_BALL =", value, "blueBall");
            return (Criteria) this;
        }

        public Criteria andBlueBallNotEqualTo(String value) {
            addCriterion("BLUE_BALL <>", value, "blueBall");
            return (Criteria) this;
        }

        public Criteria andBlueBallGreaterThan(String value) {
            addCriterion("BLUE_BALL >", value, "blueBall");
            return (Criteria) this;
        }

        public Criteria andBlueBallGreaterThanOrEqualTo(String value) {
            addCriterion("BLUE_BALL >=", value, "blueBall");
            return (Criteria) this;
        }

        public Criteria andBlueBallLessThan(String value) {
            addCriterion("BLUE_BALL <", value, "blueBall");
            return (Criteria) this;
        }

        public Criteria andBlueBallLessThanOrEqualTo(String value) {
            addCriterion("BLUE_BALL <=", value, "blueBall");
            return (Criteria) this;
        }

        public Criteria andBlueBallLike(String value) {
            addCriterion("BLUE_BALL like", value, "blueBall");
            return (Criteria) this;
        }

        public Criteria andBlueBallNotLike(String value) {
            addCriterion("BLUE_BALL not like", value, "blueBall");
            return (Criteria) this;
        }

        public Criteria andBlueBallIn(List<String> values) {
            addCriterion("BLUE_BALL in", values, "blueBall");
            return (Criteria) this;
        }

        public Criteria andBlueBallNotIn(List<String> values) {
            addCriterion("BLUE_BALL not in", values, "blueBall");
            return (Criteria) this;
        }

        public Criteria andBlueBallBetween(String value1, String value2) {
            addCriterion("BLUE_BALL between", value1, value2, "blueBall");
            return (Criteria) this;
        }

        public Criteria andBlueBallNotBetween(String value1, String value2) {
            addCriterion("BLUE_BALL not between", value1, value2, "blueBall");
            return (Criteria) this;
        }

        public Criteria andOddEvenDataIsNull() {
            addCriterion("ODD_EVEN_DATA is null");
            return (Criteria) this;
        }

        public Criteria andOddEvenDataIsNotNull() {
            addCriterion("ODD_EVEN_DATA is not null");
            return (Criteria) this;
        }

        public Criteria andOddEvenDataEqualTo(Integer value) {
            addCriterion("ODD_EVEN_DATA =", value, "oddEvenData");
            return (Criteria) this;
        }

        public Criteria andOddEvenDataNotEqualTo(Integer value) {
            addCriterion("ODD_EVEN_DATA <>", value, "oddEvenData");
            return (Criteria) this;
        }

        public Criteria andOddEvenDataGreaterThan(Integer value) {
            addCriterion("ODD_EVEN_DATA >", value, "oddEvenData");
            return (Criteria) this;
        }

        public Criteria andOddEvenDataGreaterThanOrEqualTo(Integer value) {
            addCriterion("ODD_EVEN_DATA >=", value, "oddEvenData");
            return (Criteria) this;
        }

        public Criteria andOddEvenDataLessThan(Integer value) {
            addCriterion("ODD_EVEN_DATA <", value, "oddEvenData");
            return (Criteria) this;
        }

        public Criteria andOddEvenDataLessThanOrEqualTo(Integer value) {
            addCriterion("ODD_EVEN_DATA <=", value, "oddEvenData");
            return (Criteria) this;
        }

        public Criteria andOddEvenDataIn(List<Integer> values) {
            addCriterion("ODD_EVEN_DATA in", values, "oddEvenData");
            return (Criteria) this;
        }

        public Criteria andOddEvenDataNotIn(List<Integer> values) {
            addCriterion("ODD_EVEN_DATA not in", values, "oddEvenData");
            return (Criteria) this;
        }

        public Criteria andOddEvenDataBetween(Integer value1, Integer value2) {
            addCriterion("ODD_EVEN_DATA between", value1, value2, "oddEvenData");
            return (Criteria) this;
        }

        public Criteria andOddEvenDataNotBetween(Integer value1, Integer value2) {
            addCriterion("ODD_EVEN_DATA not between", value1, value2, "oddEvenData");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNull() {
            addCriterion("CREATION_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNotNull() {
            addCriterion("CREATION_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreationDateEqualTo(Date value) {
            addCriterion("CREATION_DATE =", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotEqualTo(Date value) {
            addCriterion("CREATION_DATE <>", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThan(Date value) {
            addCriterion("CREATION_DATE >", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATION_DATE >=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThan(Date value) {
            addCriterion("CREATION_DATE <", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATION_DATE <=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateIn(List<Date> values) {
            addCriterion("CREATION_DATE in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotIn(List<Date> values) {
            addCriterion("CREATION_DATE not in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateBetween(Date value1, Date value2) {
            addCriterion("CREATION_DATE between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATION_DATE not between", value1, value2, "creationDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_period
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_period
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}