package com.fucai.model;

import java.io.Serializable;
import java.util.Date;

public class BasePeriod implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_period.PERIOD_ID
     *
     * @mbggenerated
     */
    private Integer periodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_period.PERIOD_NUMBER
     *
     * @mbggenerated
     */
    private String periodNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_period.RED_ONE_BALL
     *
     * @mbggenerated
     */
    private String redOneBall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_period.RED_TWO_BALL
     *
     * @mbggenerated
     */
    private String redTwoBall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_period.RED_THREE_BALL
     *
     * @mbggenerated
     */
    private String redThreeBall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_period.RED_FOUR_BALL
     *
     * @mbggenerated
     */
    private String redFourBall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_period.RED_FIVE_BALL
     *
     * @mbggenerated
     */
    private String redFiveBall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_period.RED_SIX_BALL
     *
     * @mbggenerated
     */
    private String redSixBall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_period.BLUE_BALL
     *
     * @mbggenerated
     */
    private String blueBall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_period.ODD_EVEN_DATA
     *
     * @mbggenerated
     */
    private Integer oddEvenData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_period.CREATION_DATE
     *
     * @mbggenerated
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_period
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_period.PERIOD_ID
     *
     * @return the value of base_period.PERIOD_ID
     *
     * @mbggenerated
     */
    public Integer getPeriodId() {
        return periodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_period.PERIOD_ID
     *
     * @param periodId the value for base_period.PERIOD_ID
     *
     * @mbggenerated
     */
    public void setPeriodId(Integer periodId) {
        this.periodId = periodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_period.PERIOD_NUMBER
     *
     * @return the value of base_period.PERIOD_NUMBER
     *
     * @mbggenerated
     */
    public String getPeriodNumber() {
        return periodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_period.PERIOD_NUMBER
     *
     * @param periodNumber the value for base_period.PERIOD_NUMBER
     *
     * @mbggenerated
     */
    public void setPeriodNumber(String periodNumber) {
        this.periodNumber = periodNumber == null ? null : periodNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_period.RED_ONE_BALL
     *
     * @return the value of base_period.RED_ONE_BALL
     *
     * @mbggenerated
     */
    public String getRedOneBall() {
        return redOneBall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_period.RED_ONE_BALL
     *
     * @param redOneBall the value for base_period.RED_ONE_BALL
     *
     * @mbggenerated
     */
    public void setRedOneBall(String redOneBall) {
        this.redOneBall = redOneBall == null ? null : redOneBall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_period.RED_TWO_BALL
     *
     * @return the value of base_period.RED_TWO_BALL
     *
     * @mbggenerated
     */
    public String getRedTwoBall() {
        return redTwoBall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_period.RED_TWO_BALL
     *
     * @param redTwoBall the value for base_period.RED_TWO_BALL
     *
     * @mbggenerated
     */
    public void setRedTwoBall(String redTwoBall) {
        this.redTwoBall = redTwoBall == null ? null : redTwoBall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_period.RED_THREE_BALL
     *
     * @return the value of base_period.RED_THREE_BALL
     *
     * @mbggenerated
     */
    public String getRedThreeBall() {
        return redThreeBall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_period.RED_THREE_BALL
     *
     * @param redThreeBall the value for base_period.RED_THREE_BALL
     *
     * @mbggenerated
     */
    public void setRedThreeBall(String redThreeBall) {
        this.redThreeBall = redThreeBall == null ? null : redThreeBall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_period.RED_FOUR_BALL
     *
     * @return the value of base_period.RED_FOUR_BALL
     *
     * @mbggenerated
     */
    public String getRedFourBall() {
        return redFourBall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_period.RED_FOUR_BALL
     *
     * @param redFourBall the value for base_period.RED_FOUR_BALL
     *
     * @mbggenerated
     */
    public void setRedFourBall(String redFourBall) {
        this.redFourBall = redFourBall == null ? null : redFourBall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_period.RED_FIVE_BALL
     *
     * @return the value of base_period.RED_FIVE_BALL
     *
     * @mbggenerated
     */
    public String getRedFiveBall() {
        return redFiveBall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_period.RED_FIVE_BALL
     *
     * @param redFiveBall the value for base_period.RED_FIVE_BALL
     *
     * @mbggenerated
     */
    public void setRedFiveBall(String redFiveBall) {
        this.redFiveBall = redFiveBall == null ? null : redFiveBall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_period.RED_SIX_BALL
     *
     * @return the value of base_period.RED_SIX_BALL
     *
     * @mbggenerated
     */
    public String getRedSixBall() {
        return redSixBall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_period.RED_SIX_BALL
     *
     * @param redSixBall the value for base_period.RED_SIX_BALL
     *
     * @mbggenerated
     */
    public void setRedSixBall(String redSixBall) {
        this.redSixBall = redSixBall == null ? null : redSixBall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_period.BLUE_BALL
     *
     * @return the value of base_period.BLUE_BALL
     *
     * @mbggenerated
     */
    public String getBlueBall() {
        return blueBall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_period.BLUE_BALL
     *
     * @param blueBall the value for base_period.BLUE_BALL
     *
     * @mbggenerated
     */
    public void setBlueBall(String blueBall) {
        this.blueBall = blueBall == null ? null : blueBall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_period.ODD_EVEN_DATA
     *
     * @return the value of base_period.ODD_EVEN_DATA
     *
     * @mbggenerated
     */
    public Integer getOddEvenData() {
        return oddEvenData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_period.ODD_EVEN_DATA
     *
     * @param oddEvenData the value for base_period.ODD_EVEN_DATA
     *
     * @mbggenerated
     */
    public void setOddEvenData(Integer oddEvenData) {
        this.oddEvenData = oddEvenData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_period.CREATION_DATE
     *
     * @return the value of base_period.CREATION_DATE
     *
     * @mbggenerated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_period.CREATION_DATE
     *
     * @param creationDate the value for base_period.CREATION_DATE
     *
     * @mbggenerated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_period
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", periodId=").append(periodId);
        sb.append(", periodNumber=").append(periodNumber);
        sb.append(", redOneBall=").append(redOneBall);
        sb.append(", redTwoBall=").append(redTwoBall);
        sb.append(", redThreeBall=").append(redThreeBall);
        sb.append(", redFourBall=").append(redFourBall);
        sb.append(", redFiveBall=").append(redFiveBall);
        sb.append(", redSixBall=").append(redSixBall);
        sb.append(", blueBall=").append(blueBall);
        sb.append(", oddEvenData=").append(oddEvenData);
        sb.append(", creationDate=").append(creationDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}