package com.fucai.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BlueBallProbabilityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    public BlueBallProbabilityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBallProbabilityIdIsNull() {
            addCriterion("BALL_PROBABILITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdIsNotNull() {
            addCriterion("BALL_PROBABILITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdEqualTo(Integer value) {
            addCriterion("BALL_PROBABILITY_ID =", value, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdNotEqualTo(Integer value) {
            addCriterion("BALL_PROBABILITY_ID <>", value, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdGreaterThan(Integer value) {
            addCriterion("BALL_PROBABILITY_ID >", value, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("BALL_PROBABILITY_ID >=", value, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdLessThan(Integer value) {
            addCriterion("BALL_PROBABILITY_ID <", value, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdLessThanOrEqualTo(Integer value) {
            addCriterion("BALL_PROBABILITY_ID <=", value, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdIn(List<Integer> values) {
            addCriterion("BALL_PROBABILITY_ID in", values, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdNotIn(List<Integer> values) {
            addCriterion("BALL_PROBABILITY_ID not in", values, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdBetween(Integer value1, Integer value2) {
            addCriterion("BALL_PROBABILITY_ID between", value1, value2, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("BALL_PROBABILITY_ID not between", value1, value2, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBlueBallOneIsNull() {
            addCriterion("BLUE_BALL_ONE is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallOneIsNotNull() {
            addCriterion("BLUE_BALL_ONE is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallOneEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_ONE =", value, "blueBallOne");
            return (Criteria) this;
        }

        public Criteria andBlueBallOneNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_ONE <>", value, "blueBallOne");
            return (Criteria) this;
        }

        public Criteria andBlueBallOneGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_ONE >", value, "blueBallOne");
            return (Criteria) this;
        }

        public Criteria andBlueBallOneGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_ONE >=", value, "blueBallOne");
            return (Criteria) this;
        }

        public Criteria andBlueBallOneLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_ONE <", value, "blueBallOne");
            return (Criteria) this;
        }

        public Criteria andBlueBallOneLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_ONE <=", value, "blueBallOne");
            return (Criteria) this;
        }

        public Criteria andBlueBallOneIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_ONE in", values, "blueBallOne");
            return (Criteria) this;
        }

        public Criteria andBlueBallOneNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_ONE not in", values, "blueBallOne");
            return (Criteria) this;
        }

        public Criteria andBlueBallOneBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_ONE between", value1, value2, "blueBallOne");
            return (Criteria) this;
        }

        public Criteria andBlueBallOneNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_ONE not between", value1, value2, "blueBallOne");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwoIsNull() {
            addCriterion("BLUE_BALL_TWO is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwoIsNotNull() {
            addCriterion("BLUE_BALL_TWO is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwoEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_TWO =", value, "blueBallTwo");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwoNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_TWO <>", value, "blueBallTwo");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwoGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_TWO >", value, "blueBallTwo");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_TWO >=", value, "blueBallTwo");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwoLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_TWO <", value, "blueBallTwo");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_TWO <=", value, "blueBallTwo");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwoIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_TWO in", values, "blueBallTwo");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwoNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_TWO not in", values, "blueBallTwo");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_TWO between", value1, value2, "blueBallTwo");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_TWO not between", value1, value2, "blueBallTwo");
            return (Criteria) this;
        }

        public Criteria andBlueBallThreeIsNull() {
            addCriterion("BLUE_BALL_THREE is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallThreeIsNotNull() {
            addCriterion("BLUE_BALL_THREE is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallThreeEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_THREE =", value, "blueBallThree");
            return (Criteria) this;
        }

        public Criteria andBlueBallThreeNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_THREE <>", value, "blueBallThree");
            return (Criteria) this;
        }

        public Criteria andBlueBallThreeGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_THREE >", value, "blueBallThree");
            return (Criteria) this;
        }

        public Criteria andBlueBallThreeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_THREE >=", value, "blueBallThree");
            return (Criteria) this;
        }

        public Criteria andBlueBallThreeLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_THREE <", value, "blueBallThree");
            return (Criteria) this;
        }

        public Criteria andBlueBallThreeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_THREE <=", value, "blueBallThree");
            return (Criteria) this;
        }

        public Criteria andBlueBallThreeIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_THREE in", values, "blueBallThree");
            return (Criteria) this;
        }

        public Criteria andBlueBallThreeNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_THREE not in", values, "blueBallThree");
            return (Criteria) this;
        }

        public Criteria andBlueBallThreeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_THREE between", value1, value2, "blueBallThree");
            return (Criteria) this;
        }

        public Criteria andBlueBallThreeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_THREE not between", value1, value2, "blueBallThree");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourIsNull() {
            addCriterion("BLUE_BALL_FOUR is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourIsNotNull() {
            addCriterion("BLUE_BALL_FOUR is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FOUR =", value, "blueBallFour");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FOUR <>", value, "blueBallFour");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_FOUR >", value, "blueBallFour");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FOUR >=", value, "blueBallFour");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_FOUR <", value, "blueBallFour");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FOUR <=", value, "blueBallFour");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_FOUR in", values, "blueBallFour");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_FOUR not in", values, "blueBallFour");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_FOUR between", value1, value2, "blueBallFour");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_FOUR not between", value1, value2, "blueBallFour");
            return (Criteria) this;
        }

        public Criteria andBlueBallFiveIsNull() {
            addCriterion("BLUE_BALL_FIVE is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallFiveIsNotNull() {
            addCriterion("BLUE_BALL_FIVE is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallFiveEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FIVE =", value, "blueBallFive");
            return (Criteria) this;
        }

        public Criteria andBlueBallFiveNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FIVE <>", value, "blueBallFive");
            return (Criteria) this;
        }

        public Criteria andBlueBallFiveGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_FIVE >", value, "blueBallFive");
            return (Criteria) this;
        }

        public Criteria andBlueBallFiveGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FIVE >=", value, "blueBallFive");
            return (Criteria) this;
        }

        public Criteria andBlueBallFiveLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_FIVE <", value, "blueBallFive");
            return (Criteria) this;
        }

        public Criteria andBlueBallFiveLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FIVE <=", value, "blueBallFive");
            return (Criteria) this;
        }

        public Criteria andBlueBallFiveIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_FIVE in", values, "blueBallFive");
            return (Criteria) this;
        }

        public Criteria andBlueBallFiveNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_FIVE not in", values, "blueBallFive");
            return (Criteria) this;
        }

        public Criteria andBlueBallFiveBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_FIVE between", value1, value2, "blueBallFive");
            return (Criteria) this;
        }

        public Criteria andBlueBallFiveNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_FIVE not between", value1, value2, "blueBallFive");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixIsNull() {
            addCriterion("BLUE_BALL_SIX is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixIsNotNull() {
            addCriterion("BLUE_BALL_SIX is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_SIX =", value, "blueBallSix");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_SIX <>", value, "blueBallSix");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_SIX >", value, "blueBallSix");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_SIX >=", value, "blueBallSix");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_SIX <", value, "blueBallSix");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_SIX <=", value, "blueBallSix");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_SIX in", values, "blueBallSix");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_SIX not in", values, "blueBallSix");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_SIX between", value1, value2, "blueBallSix");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_SIX not between", value1, value2, "blueBallSix");
            return (Criteria) this;
        }

        public Criteria andBlueBallSevenIsNull() {
            addCriterion("BLUE_BALL_SEVEN is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallSevenIsNotNull() {
            addCriterion("BLUE_BALL_SEVEN is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallSevenEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_SEVEN =", value, "blueBallSeven");
            return (Criteria) this;
        }

        public Criteria andBlueBallSevenNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_SEVEN <>", value, "blueBallSeven");
            return (Criteria) this;
        }

        public Criteria andBlueBallSevenGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_SEVEN >", value, "blueBallSeven");
            return (Criteria) this;
        }

        public Criteria andBlueBallSevenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_SEVEN >=", value, "blueBallSeven");
            return (Criteria) this;
        }

        public Criteria andBlueBallSevenLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_SEVEN <", value, "blueBallSeven");
            return (Criteria) this;
        }

        public Criteria andBlueBallSevenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_SEVEN <=", value, "blueBallSeven");
            return (Criteria) this;
        }

        public Criteria andBlueBallSevenIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_SEVEN in", values, "blueBallSeven");
            return (Criteria) this;
        }

        public Criteria andBlueBallSevenNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_SEVEN not in", values, "blueBallSeven");
            return (Criteria) this;
        }

        public Criteria andBlueBallSevenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_SEVEN between", value1, value2, "blueBallSeven");
            return (Criteria) this;
        }

        public Criteria andBlueBallSevenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_SEVEN not between", value1, value2, "blueBallSeven");
            return (Criteria) this;
        }

        public Criteria andBlueBallEightIsNull() {
            addCriterion("BLUE_BALL_EIGHT is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallEightIsNotNull() {
            addCriterion("BLUE_BALL_EIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallEightEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_EIGHT =", value, "blueBallEight");
            return (Criteria) this;
        }

        public Criteria andBlueBallEightNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_EIGHT <>", value, "blueBallEight");
            return (Criteria) this;
        }

        public Criteria andBlueBallEightGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_EIGHT >", value, "blueBallEight");
            return (Criteria) this;
        }

        public Criteria andBlueBallEightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_EIGHT >=", value, "blueBallEight");
            return (Criteria) this;
        }

        public Criteria andBlueBallEightLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_EIGHT <", value, "blueBallEight");
            return (Criteria) this;
        }

        public Criteria andBlueBallEightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_EIGHT <=", value, "blueBallEight");
            return (Criteria) this;
        }

        public Criteria andBlueBallEightIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_EIGHT in", values, "blueBallEight");
            return (Criteria) this;
        }

        public Criteria andBlueBallEightNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_EIGHT not in", values, "blueBallEight");
            return (Criteria) this;
        }

        public Criteria andBlueBallEightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_EIGHT between", value1, value2, "blueBallEight");
            return (Criteria) this;
        }

        public Criteria andBlueBallEightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_EIGHT not between", value1, value2, "blueBallEight");
            return (Criteria) this;
        }

        public Criteria andBlueBallNineIsNull() {
            addCriterion("BLUE_BALL_NINE is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallNineIsNotNull() {
            addCriterion("BLUE_BALL_NINE is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallNineEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_NINE =", value, "blueBallNine");
            return (Criteria) this;
        }

        public Criteria andBlueBallNineNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_NINE <>", value, "blueBallNine");
            return (Criteria) this;
        }

        public Criteria andBlueBallNineGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_NINE >", value, "blueBallNine");
            return (Criteria) this;
        }

        public Criteria andBlueBallNineGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_NINE >=", value, "blueBallNine");
            return (Criteria) this;
        }

        public Criteria andBlueBallNineLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_NINE <", value, "blueBallNine");
            return (Criteria) this;
        }

        public Criteria andBlueBallNineLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_NINE <=", value, "blueBallNine");
            return (Criteria) this;
        }

        public Criteria andBlueBallNineIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_NINE in", values, "blueBallNine");
            return (Criteria) this;
        }

        public Criteria andBlueBallNineNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_NINE not in", values, "blueBallNine");
            return (Criteria) this;
        }

        public Criteria andBlueBallNineBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_NINE between", value1, value2, "blueBallNine");
            return (Criteria) this;
        }

        public Criteria andBlueBallNineNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_NINE not between", value1, value2, "blueBallNine");
            return (Criteria) this;
        }

        public Criteria andBlueBallTenIsNull() {
            addCriterion("BLUE_BALL_TEN is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallTenIsNotNull() {
            addCriterion("BLUE_BALL_TEN is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallTenEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_TEN =", value, "blueBallTen");
            return (Criteria) this;
        }

        public Criteria andBlueBallTenNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_TEN <>", value, "blueBallTen");
            return (Criteria) this;
        }

        public Criteria andBlueBallTenGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_TEN >", value, "blueBallTen");
            return (Criteria) this;
        }

        public Criteria andBlueBallTenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_TEN >=", value, "blueBallTen");
            return (Criteria) this;
        }

        public Criteria andBlueBallTenLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_TEN <", value, "blueBallTen");
            return (Criteria) this;
        }

        public Criteria andBlueBallTenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_TEN <=", value, "blueBallTen");
            return (Criteria) this;
        }

        public Criteria andBlueBallTenIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_TEN in", values, "blueBallTen");
            return (Criteria) this;
        }

        public Criteria andBlueBallTenNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_TEN not in", values, "blueBallTen");
            return (Criteria) this;
        }

        public Criteria andBlueBallTenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_TEN between", value1, value2, "blueBallTen");
            return (Criteria) this;
        }

        public Criteria andBlueBallTenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_TEN not between", value1, value2, "blueBallTen");
            return (Criteria) this;
        }

        public Criteria andBlueBallElevenIsNull() {
            addCriterion("BLUE_BALL_ELEVEN is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallElevenIsNotNull() {
            addCriterion("BLUE_BALL_ELEVEN is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallElevenEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_ELEVEN =", value, "blueBallEleven");
            return (Criteria) this;
        }

        public Criteria andBlueBallElevenNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_ELEVEN <>", value, "blueBallEleven");
            return (Criteria) this;
        }

        public Criteria andBlueBallElevenGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_ELEVEN >", value, "blueBallEleven");
            return (Criteria) this;
        }

        public Criteria andBlueBallElevenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_ELEVEN >=", value, "blueBallEleven");
            return (Criteria) this;
        }

        public Criteria andBlueBallElevenLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_ELEVEN <", value, "blueBallEleven");
            return (Criteria) this;
        }

        public Criteria andBlueBallElevenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_ELEVEN <=", value, "blueBallEleven");
            return (Criteria) this;
        }

        public Criteria andBlueBallElevenIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_ELEVEN in", values, "blueBallEleven");
            return (Criteria) this;
        }

        public Criteria andBlueBallElevenNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_ELEVEN not in", values, "blueBallEleven");
            return (Criteria) this;
        }

        public Criteria andBlueBallElevenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_ELEVEN between", value1, value2, "blueBallEleven");
            return (Criteria) this;
        }

        public Criteria andBlueBallElevenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_ELEVEN not between", value1, value2, "blueBallEleven");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwelveIsNull() {
            addCriterion("BLUE_BALL_TWELVE is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwelveIsNotNull() {
            addCriterion("BLUE_BALL_TWELVE is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwelveEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_TWELVE =", value, "blueBallTwelve");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwelveNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_TWELVE <>", value, "blueBallTwelve");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwelveGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_TWELVE >", value, "blueBallTwelve");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwelveGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_TWELVE >=", value, "blueBallTwelve");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwelveLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_TWELVE <", value, "blueBallTwelve");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwelveLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_TWELVE <=", value, "blueBallTwelve");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwelveIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_TWELVE in", values, "blueBallTwelve");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwelveNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_TWELVE not in", values, "blueBallTwelve");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwelveBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_TWELVE between", value1, value2, "blueBallTwelve");
            return (Criteria) this;
        }

        public Criteria andBlueBallTwelveNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_TWELVE not between", value1, value2, "blueBallTwelve");
            return (Criteria) this;
        }

        public Criteria andBlueBallThirteenIsNull() {
            addCriterion("BLUE_BALL_THIRTEEN is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallThirteenIsNotNull() {
            addCriterion("BLUE_BALL_THIRTEEN is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallThirteenEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_THIRTEEN =", value, "blueBallThirteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallThirteenNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_THIRTEEN <>", value, "blueBallThirteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallThirteenGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_THIRTEEN >", value, "blueBallThirteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallThirteenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_THIRTEEN >=", value, "blueBallThirteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallThirteenLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_THIRTEEN <", value, "blueBallThirteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallThirteenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_THIRTEEN <=", value, "blueBallThirteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallThirteenIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_THIRTEEN in", values, "blueBallThirteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallThirteenNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_THIRTEEN not in", values, "blueBallThirteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallThirteenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_THIRTEEN between", value1, value2, "blueBallThirteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallThirteenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_THIRTEEN not between", value1, value2, "blueBallThirteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourteenIsNull() {
            addCriterion("BLUE_BALL_FOURTEEN is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourteenIsNotNull() {
            addCriterion("BLUE_BALL_FOURTEEN is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourteenEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FOURTEEN =", value, "blueBallFourteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourteenNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FOURTEEN <>", value, "blueBallFourteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourteenGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_FOURTEEN >", value, "blueBallFourteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourteenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FOURTEEN >=", value, "blueBallFourteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourteenLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_FOURTEEN <", value, "blueBallFourteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourteenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FOURTEEN <=", value, "blueBallFourteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourteenIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_FOURTEEN in", values, "blueBallFourteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourteenNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_FOURTEEN not in", values, "blueBallFourteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourteenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_FOURTEEN between", value1, value2, "blueBallFourteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFourteenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_FOURTEEN not between", value1, value2, "blueBallFourteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFifteenIsNull() {
            addCriterion("BLUE_BALL_FIFTEEN is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallFifteenIsNotNull() {
            addCriterion("BLUE_BALL_FIFTEEN is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallFifteenEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FIFTEEN =", value, "blueBallFifteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFifteenNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FIFTEEN <>", value, "blueBallFifteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFifteenGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_FIFTEEN >", value, "blueBallFifteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFifteenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FIFTEEN >=", value, "blueBallFifteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFifteenLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_FIFTEEN <", value, "blueBallFifteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFifteenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_FIFTEEN <=", value, "blueBallFifteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFifteenIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_FIFTEEN in", values, "blueBallFifteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFifteenNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_FIFTEEN not in", values, "blueBallFifteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFifteenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_FIFTEEN between", value1, value2, "blueBallFifteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallFifteenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_FIFTEEN not between", value1, value2, "blueBallFifteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixteenIsNull() {
            addCriterion("BLUE_BALL_SIXTEEN is null");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixteenIsNotNull() {
            addCriterion("BLUE_BALL_SIXTEEN is not null");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixteenEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_SIXTEEN =", value, "blueBallSixteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixteenNotEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_SIXTEEN <>", value, "blueBallSixteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixteenGreaterThan(BigDecimal value) {
            addCriterion("BLUE_BALL_SIXTEEN >", value, "blueBallSixteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixteenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_SIXTEEN >=", value, "blueBallSixteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixteenLessThan(BigDecimal value) {
            addCriterion("BLUE_BALL_SIXTEEN <", value, "blueBallSixteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixteenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLUE_BALL_SIXTEEN <=", value, "blueBallSixteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixteenIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_SIXTEEN in", values, "blueBallSixteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixteenNotIn(List<BigDecimal> values) {
            addCriterion("BLUE_BALL_SIXTEEN not in", values, "blueBallSixteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixteenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_SIXTEEN between", value1, value2, "blueBallSixteen");
            return (Criteria) this;
        }

        public Criteria andBlueBallSixteenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLUE_BALL_SIXTEEN not between", value1, value2, "blueBallSixteen");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("LAST_UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("LAST_UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(Date value) {
            addCriterion("LAST_UPDATE_DATE >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(Date value) {
            addCriterion("LAST_UPDATE_DATE <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blue_ball_probability
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}