package com.fucai.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class BlueBallProbability implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BALL_PROBABILITY_ID
     *
     * @mbggenerated
     */
    private Integer ballProbabilityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_ONE
     *
     * @mbggenerated
     */
    private BigDecimal blueBallOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_TWO
     *
     * @mbggenerated
     */
    private BigDecimal blueBallTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_THREE
     *
     * @mbggenerated
     */
    private BigDecimal blueBallThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_FOUR
     *
     * @mbggenerated
     */
    private BigDecimal blueBallFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_FIVE
     *
     * @mbggenerated
     */
    private BigDecimal blueBallFive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_SIX
     *
     * @mbggenerated
     */
    private BigDecimal blueBallSix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_SEVEN
     *
     * @mbggenerated
     */
    private BigDecimal blueBallSeven;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_EIGHT
     *
     * @mbggenerated
     */
    private BigDecimal blueBallEight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_NINE
     *
     * @mbggenerated
     */
    private BigDecimal blueBallNine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_TEN
     *
     * @mbggenerated
     */
    private BigDecimal blueBallTen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_ELEVEN
     *
     * @mbggenerated
     */
    private BigDecimal blueBallEleven;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_TWELVE
     *
     * @mbggenerated
     */
    private BigDecimal blueBallTwelve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_THIRTEEN
     *
     * @mbggenerated
     */
    private BigDecimal blueBallThirteen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_FOURTEEN
     *
     * @mbggenerated
     */
    private BigDecimal blueBallFourteen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_FIFTEEN
     *
     * @mbggenerated
     */
    private BigDecimal blueBallFifteen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.BLUE_BALL_SIXTEEN
     *
     * @mbggenerated
     */
    private BigDecimal blueBallSixteen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blue_ball_probability.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BALL_PROBABILITY_ID
     *
     * @return the value of blue_ball_probability.BALL_PROBABILITY_ID
     *
     * @mbggenerated
     */
    public Integer getBallProbabilityId() {
        return ballProbabilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BALL_PROBABILITY_ID
     *
     * @param ballProbabilityId the value for blue_ball_probability.BALL_PROBABILITY_ID
     *
     * @mbggenerated
     */
    public void setBallProbabilityId(Integer ballProbabilityId) {
        this.ballProbabilityId = ballProbabilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_ONE
     *
     * @return the value of blue_ball_probability.BLUE_BALL_ONE
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallOne() {
        return blueBallOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_ONE
     *
     * @param blueBallOne the value for blue_ball_probability.BLUE_BALL_ONE
     *
     * @mbggenerated
     */
    public void setBlueBallOne(BigDecimal blueBallOne) {
        this.blueBallOne = blueBallOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_TWO
     *
     * @return the value of blue_ball_probability.BLUE_BALL_TWO
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallTwo() {
        return blueBallTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_TWO
     *
     * @param blueBallTwo the value for blue_ball_probability.BLUE_BALL_TWO
     *
     * @mbggenerated
     */
    public void setBlueBallTwo(BigDecimal blueBallTwo) {
        this.blueBallTwo = blueBallTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_THREE
     *
     * @return the value of blue_ball_probability.BLUE_BALL_THREE
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallThree() {
        return blueBallThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_THREE
     *
     * @param blueBallThree the value for blue_ball_probability.BLUE_BALL_THREE
     *
     * @mbggenerated
     */
    public void setBlueBallThree(BigDecimal blueBallThree) {
        this.blueBallThree = blueBallThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_FOUR
     *
     * @return the value of blue_ball_probability.BLUE_BALL_FOUR
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallFour() {
        return blueBallFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_FOUR
     *
     * @param blueBallFour the value for blue_ball_probability.BLUE_BALL_FOUR
     *
     * @mbggenerated
     */
    public void setBlueBallFour(BigDecimal blueBallFour) {
        this.blueBallFour = blueBallFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_FIVE
     *
     * @return the value of blue_ball_probability.BLUE_BALL_FIVE
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallFive() {
        return blueBallFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_FIVE
     *
     * @param blueBallFive the value for blue_ball_probability.BLUE_BALL_FIVE
     *
     * @mbggenerated
     */
    public void setBlueBallFive(BigDecimal blueBallFive) {
        this.blueBallFive = blueBallFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_SIX
     *
     * @return the value of blue_ball_probability.BLUE_BALL_SIX
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallSix() {
        return blueBallSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_SIX
     *
     * @param blueBallSix the value for blue_ball_probability.BLUE_BALL_SIX
     *
     * @mbggenerated
     */
    public void setBlueBallSix(BigDecimal blueBallSix) {
        this.blueBallSix = blueBallSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_SEVEN
     *
     * @return the value of blue_ball_probability.BLUE_BALL_SEVEN
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallSeven() {
        return blueBallSeven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_SEVEN
     *
     * @param blueBallSeven the value for blue_ball_probability.BLUE_BALL_SEVEN
     *
     * @mbggenerated
     */
    public void setBlueBallSeven(BigDecimal blueBallSeven) {
        this.blueBallSeven = blueBallSeven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_EIGHT
     *
     * @return the value of blue_ball_probability.BLUE_BALL_EIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallEight() {
        return blueBallEight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_EIGHT
     *
     * @param blueBallEight the value for blue_ball_probability.BLUE_BALL_EIGHT
     *
     * @mbggenerated
     */
    public void setBlueBallEight(BigDecimal blueBallEight) {
        this.blueBallEight = blueBallEight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_NINE
     *
     * @return the value of blue_ball_probability.BLUE_BALL_NINE
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallNine() {
        return blueBallNine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_NINE
     *
     * @param blueBallNine the value for blue_ball_probability.BLUE_BALL_NINE
     *
     * @mbggenerated
     */
    public void setBlueBallNine(BigDecimal blueBallNine) {
        this.blueBallNine = blueBallNine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_TEN
     *
     * @return the value of blue_ball_probability.BLUE_BALL_TEN
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallTen() {
        return blueBallTen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_TEN
     *
     * @param blueBallTen the value for blue_ball_probability.BLUE_BALL_TEN
     *
     * @mbggenerated
     */
    public void setBlueBallTen(BigDecimal blueBallTen) {
        this.blueBallTen = blueBallTen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_ELEVEN
     *
     * @return the value of blue_ball_probability.BLUE_BALL_ELEVEN
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallEleven() {
        return blueBallEleven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_ELEVEN
     *
     * @param blueBallEleven the value for blue_ball_probability.BLUE_BALL_ELEVEN
     *
     * @mbggenerated
     */
    public void setBlueBallEleven(BigDecimal blueBallEleven) {
        this.blueBallEleven = blueBallEleven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_TWELVE
     *
     * @return the value of blue_ball_probability.BLUE_BALL_TWELVE
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallTwelve() {
        return blueBallTwelve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_TWELVE
     *
     * @param blueBallTwelve the value for blue_ball_probability.BLUE_BALL_TWELVE
     *
     * @mbggenerated
     */
    public void setBlueBallTwelve(BigDecimal blueBallTwelve) {
        this.blueBallTwelve = blueBallTwelve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_THIRTEEN
     *
     * @return the value of blue_ball_probability.BLUE_BALL_THIRTEEN
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallThirteen() {
        return blueBallThirteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_THIRTEEN
     *
     * @param blueBallThirteen the value for blue_ball_probability.BLUE_BALL_THIRTEEN
     *
     * @mbggenerated
     */
    public void setBlueBallThirteen(BigDecimal blueBallThirteen) {
        this.blueBallThirteen = blueBallThirteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_FOURTEEN
     *
     * @return the value of blue_ball_probability.BLUE_BALL_FOURTEEN
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallFourteen() {
        return blueBallFourteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_FOURTEEN
     *
     * @param blueBallFourteen the value for blue_ball_probability.BLUE_BALL_FOURTEEN
     *
     * @mbggenerated
     */
    public void setBlueBallFourteen(BigDecimal blueBallFourteen) {
        this.blueBallFourteen = blueBallFourteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_FIFTEEN
     *
     * @return the value of blue_ball_probability.BLUE_BALL_FIFTEEN
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallFifteen() {
        return blueBallFifteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_FIFTEEN
     *
     * @param blueBallFifteen the value for blue_ball_probability.BLUE_BALL_FIFTEEN
     *
     * @mbggenerated
     */
    public void setBlueBallFifteen(BigDecimal blueBallFifteen) {
        this.blueBallFifteen = blueBallFifteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.BLUE_BALL_SIXTEEN
     *
     * @return the value of blue_ball_probability.BLUE_BALL_SIXTEEN
     *
     * @mbggenerated
     */
    public BigDecimal getBlueBallSixteen() {
        return blueBallSixteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.BLUE_BALL_SIXTEEN
     *
     * @param blueBallSixteen the value for blue_ball_probability.BLUE_BALL_SIXTEEN
     *
     * @mbggenerated
     */
    public void setBlueBallSixteen(BigDecimal blueBallSixteen) {
        this.blueBallSixteen = blueBallSixteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blue_ball_probability.LAST_UPDATE_DATE
     *
     * @return the value of blue_ball_probability.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blue_ball_probability.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for blue_ball_probability.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_ball_probability
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ballProbabilityId=").append(ballProbabilityId);
        sb.append(", blueBallOne=").append(blueBallOne);
        sb.append(", blueBallTwo=").append(blueBallTwo);
        sb.append(", blueBallThree=").append(blueBallThree);
        sb.append(", blueBallFour=").append(blueBallFour);
        sb.append(", blueBallFive=").append(blueBallFive);
        sb.append(", blueBallSix=").append(blueBallSix);
        sb.append(", blueBallSeven=").append(blueBallSeven);
        sb.append(", blueBallEight=").append(blueBallEight);
        sb.append(", blueBallNine=").append(blueBallNine);
        sb.append(", blueBallTen=").append(blueBallTen);
        sb.append(", blueBallEleven=").append(blueBallEleven);
        sb.append(", blueBallTwelve=").append(blueBallTwelve);
        sb.append(", blueBallThirteen=").append(blueBallThirteen);
        sb.append(", blueBallFourteen=").append(blueBallFourteen);
        sb.append(", blueBallFifteen=").append(blueBallFifteen);
        sb.append(", blueBallSixteen=").append(blueBallSixteen);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}