package com.fucai.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DataLocationProbabilityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    public DataLocationProbabilityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDataLocationProbabilityIdIsNull() {
            addCriterion("DATA_LOCATION_PROBABILITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andDataLocationProbabilityIdIsNotNull() {
            addCriterion("DATA_LOCATION_PROBABILITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDataLocationProbabilityIdEqualTo(Integer value) {
            addCriterion("DATA_LOCATION_PROBABILITY_ID =", value, "dataLocationProbabilityId");
            return (Criteria) this;
        }

        public Criteria andDataLocationProbabilityIdNotEqualTo(Integer value) {
            addCriterion("DATA_LOCATION_PROBABILITY_ID <>", value, "dataLocationProbabilityId");
            return (Criteria) this;
        }

        public Criteria andDataLocationProbabilityIdGreaterThan(Integer value) {
            addCriterion("DATA_LOCATION_PROBABILITY_ID >", value, "dataLocationProbabilityId");
            return (Criteria) this;
        }

        public Criteria andDataLocationProbabilityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("DATA_LOCATION_PROBABILITY_ID >=", value, "dataLocationProbabilityId");
            return (Criteria) this;
        }

        public Criteria andDataLocationProbabilityIdLessThan(Integer value) {
            addCriterion("DATA_LOCATION_PROBABILITY_ID <", value, "dataLocationProbabilityId");
            return (Criteria) this;
        }

        public Criteria andDataLocationProbabilityIdLessThanOrEqualTo(Integer value) {
            addCriterion("DATA_LOCATION_PROBABILITY_ID <=", value, "dataLocationProbabilityId");
            return (Criteria) this;
        }

        public Criteria andDataLocationProbabilityIdIn(List<Integer> values) {
            addCriterion("DATA_LOCATION_PROBABILITY_ID in", values, "dataLocationProbabilityId");
            return (Criteria) this;
        }

        public Criteria andDataLocationProbabilityIdNotIn(List<Integer> values) {
            addCriterion("DATA_LOCATION_PROBABILITY_ID not in", values, "dataLocationProbabilityId");
            return (Criteria) this;
        }

        public Criteria andDataLocationProbabilityIdBetween(Integer value1, Integer value2) {
            addCriterion("DATA_LOCATION_PROBABILITY_ID between", value1, value2, "dataLocationProbabilityId");
            return (Criteria) this;
        }

        public Criteria andDataLocationProbabilityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("DATA_LOCATION_PROBABILITY_ID not between", value1, value2, "dataLocationProbabilityId");
            return (Criteria) this;
        }

        public Criteria andAppearDataIsNull() {
            addCriterion("APPEAR_DATA is null");
            return (Criteria) this;
        }

        public Criteria andAppearDataIsNotNull() {
            addCriterion("APPEAR_DATA is not null");
            return (Criteria) this;
        }

        public Criteria andAppearDataEqualTo(String value) {
            addCriterion("APPEAR_DATA =", value, "appearData");
            return (Criteria) this;
        }

        public Criteria andAppearDataNotEqualTo(String value) {
            addCriterion("APPEAR_DATA <>", value, "appearData");
            return (Criteria) this;
        }

        public Criteria andAppearDataGreaterThan(String value) {
            addCriterion("APPEAR_DATA >", value, "appearData");
            return (Criteria) this;
        }

        public Criteria andAppearDataGreaterThanOrEqualTo(String value) {
            addCriterion("APPEAR_DATA >=", value, "appearData");
            return (Criteria) this;
        }

        public Criteria andAppearDataLessThan(String value) {
            addCriterion("APPEAR_DATA <", value, "appearData");
            return (Criteria) this;
        }

        public Criteria andAppearDataLessThanOrEqualTo(String value) {
            addCriterion("APPEAR_DATA <=", value, "appearData");
            return (Criteria) this;
        }

        public Criteria andAppearDataLike(String value) {
            addCriterion("APPEAR_DATA like", value, "appearData");
            return (Criteria) this;
        }

        public Criteria andAppearDataNotLike(String value) {
            addCriterion("APPEAR_DATA not like", value, "appearData");
            return (Criteria) this;
        }

        public Criteria andAppearDataIn(List<String> values) {
            addCriterion("APPEAR_DATA in", values, "appearData");
            return (Criteria) this;
        }

        public Criteria andAppearDataNotIn(List<String> values) {
            addCriterion("APPEAR_DATA not in", values, "appearData");
            return (Criteria) this;
        }

        public Criteria andAppearDataBetween(String value1, String value2) {
            addCriterion("APPEAR_DATA between", value1, value2, "appearData");
            return (Criteria) this;
        }

        public Criteria andAppearDataNotBetween(String value1, String value2) {
            addCriterion("APPEAR_DATA not between", value1, value2, "appearData");
            return (Criteria) this;
        }

        public Criteria andLocationOneProbabilityIsNull() {
            addCriterion("LOCATION_ONE_PROBABILITY is null");
            return (Criteria) this;
        }

        public Criteria andLocationOneProbabilityIsNotNull() {
            addCriterion("LOCATION_ONE_PROBABILITY is not null");
            return (Criteria) this;
        }

        public Criteria andLocationOneProbabilityEqualTo(BigDecimal value) {
            addCriterion("LOCATION_ONE_PROBABILITY =", value, "locationOneProbability");
            return (Criteria) this;
        }

        public Criteria andLocationOneProbabilityNotEqualTo(BigDecimal value) {
            addCriterion("LOCATION_ONE_PROBABILITY <>", value, "locationOneProbability");
            return (Criteria) this;
        }

        public Criteria andLocationOneProbabilityGreaterThan(BigDecimal value) {
            addCriterion("LOCATION_ONE_PROBABILITY >", value, "locationOneProbability");
            return (Criteria) this;
        }

        public Criteria andLocationOneProbabilityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LOCATION_ONE_PROBABILITY >=", value, "locationOneProbability");
            return (Criteria) this;
        }

        public Criteria andLocationOneProbabilityLessThan(BigDecimal value) {
            addCriterion("LOCATION_ONE_PROBABILITY <", value, "locationOneProbability");
            return (Criteria) this;
        }

        public Criteria andLocationOneProbabilityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LOCATION_ONE_PROBABILITY <=", value, "locationOneProbability");
            return (Criteria) this;
        }

        public Criteria andLocationOneProbabilityIn(List<BigDecimal> values) {
            addCriterion("LOCATION_ONE_PROBABILITY in", values, "locationOneProbability");
            return (Criteria) this;
        }

        public Criteria andLocationOneProbabilityNotIn(List<BigDecimal> values) {
            addCriterion("LOCATION_ONE_PROBABILITY not in", values, "locationOneProbability");
            return (Criteria) this;
        }

        public Criteria andLocationOneProbabilityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOCATION_ONE_PROBABILITY between", value1, value2, "locationOneProbability");
            return (Criteria) this;
        }

        public Criteria andLocationOneProbabilityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOCATION_ONE_PROBABILITY not between", value1, value2, "locationOneProbability");
            return (Criteria) this;
        }

        public Criteria andLocationTwoProbabilityIsNull() {
            addCriterion("LOCATION_TWO_PROBABILITY is null");
            return (Criteria) this;
        }

        public Criteria andLocationTwoProbabilityIsNotNull() {
            addCriterion("LOCATION_TWO_PROBABILITY is not null");
            return (Criteria) this;
        }

        public Criteria andLocationTwoProbabilityEqualTo(BigDecimal value) {
            addCriterion("LOCATION_TWO_PROBABILITY =", value, "locationTwoProbability");
            return (Criteria) this;
        }

        public Criteria andLocationTwoProbabilityNotEqualTo(BigDecimal value) {
            addCriterion("LOCATION_TWO_PROBABILITY <>", value, "locationTwoProbability");
            return (Criteria) this;
        }

        public Criteria andLocationTwoProbabilityGreaterThan(BigDecimal value) {
            addCriterion("LOCATION_TWO_PROBABILITY >", value, "locationTwoProbability");
            return (Criteria) this;
        }

        public Criteria andLocationTwoProbabilityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LOCATION_TWO_PROBABILITY >=", value, "locationTwoProbability");
            return (Criteria) this;
        }

        public Criteria andLocationTwoProbabilityLessThan(BigDecimal value) {
            addCriterion("LOCATION_TWO_PROBABILITY <", value, "locationTwoProbability");
            return (Criteria) this;
        }

        public Criteria andLocationTwoProbabilityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LOCATION_TWO_PROBABILITY <=", value, "locationTwoProbability");
            return (Criteria) this;
        }

        public Criteria andLocationTwoProbabilityIn(List<BigDecimal> values) {
            addCriterion("LOCATION_TWO_PROBABILITY in", values, "locationTwoProbability");
            return (Criteria) this;
        }

        public Criteria andLocationTwoProbabilityNotIn(List<BigDecimal> values) {
            addCriterion("LOCATION_TWO_PROBABILITY not in", values, "locationTwoProbability");
            return (Criteria) this;
        }

        public Criteria andLocationTwoProbabilityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOCATION_TWO_PROBABILITY between", value1, value2, "locationTwoProbability");
            return (Criteria) this;
        }

        public Criteria andLocationTwoProbabilityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOCATION_TWO_PROBABILITY not between", value1, value2, "locationTwoProbability");
            return (Criteria) this;
        }

        public Criteria andLocationThreeProbabilityIsNull() {
            addCriterion("LOCATION_THREE_PROBABILITY is null");
            return (Criteria) this;
        }

        public Criteria andLocationThreeProbabilityIsNotNull() {
            addCriterion("LOCATION_THREE_PROBABILITY is not null");
            return (Criteria) this;
        }

        public Criteria andLocationThreeProbabilityEqualTo(BigDecimal value) {
            addCriterion("LOCATION_THREE_PROBABILITY =", value, "locationThreeProbability");
            return (Criteria) this;
        }

        public Criteria andLocationThreeProbabilityNotEqualTo(BigDecimal value) {
            addCriterion("LOCATION_THREE_PROBABILITY <>", value, "locationThreeProbability");
            return (Criteria) this;
        }

        public Criteria andLocationThreeProbabilityGreaterThan(BigDecimal value) {
            addCriterion("LOCATION_THREE_PROBABILITY >", value, "locationThreeProbability");
            return (Criteria) this;
        }

        public Criteria andLocationThreeProbabilityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LOCATION_THREE_PROBABILITY >=", value, "locationThreeProbability");
            return (Criteria) this;
        }

        public Criteria andLocationThreeProbabilityLessThan(BigDecimal value) {
            addCriterion("LOCATION_THREE_PROBABILITY <", value, "locationThreeProbability");
            return (Criteria) this;
        }

        public Criteria andLocationThreeProbabilityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LOCATION_THREE_PROBABILITY <=", value, "locationThreeProbability");
            return (Criteria) this;
        }

        public Criteria andLocationThreeProbabilityIn(List<BigDecimal> values) {
            addCriterion("LOCATION_THREE_PROBABILITY in", values, "locationThreeProbability");
            return (Criteria) this;
        }

        public Criteria andLocationThreeProbabilityNotIn(List<BigDecimal> values) {
            addCriterion("LOCATION_THREE_PROBABILITY not in", values, "locationThreeProbability");
            return (Criteria) this;
        }

        public Criteria andLocationThreeProbabilityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOCATION_THREE_PROBABILITY between", value1, value2, "locationThreeProbability");
            return (Criteria) this;
        }

        public Criteria andLocationThreeProbabilityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOCATION_THREE_PROBABILITY not between", value1, value2, "locationThreeProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFourProbabilityIsNull() {
            addCriterion("LOCATION_FOUR_PROBABILITY is null");
            return (Criteria) this;
        }

        public Criteria andLocationFourProbabilityIsNotNull() {
            addCriterion("LOCATION_FOUR_PROBABILITY is not null");
            return (Criteria) this;
        }

        public Criteria andLocationFourProbabilityEqualTo(BigDecimal value) {
            addCriterion("LOCATION_FOUR_PROBABILITY =", value, "locationFourProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFourProbabilityNotEqualTo(BigDecimal value) {
            addCriterion("LOCATION_FOUR_PROBABILITY <>", value, "locationFourProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFourProbabilityGreaterThan(BigDecimal value) {
            addCriterion("LOCATION_FOUR_PROBABILITY >", value, "locationFourProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFourProbabilityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LOCATION_FOUR_PROBABILITY >=", value, "locationFourProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFourProbabilityLessThan(BigDecimal value) {
            addCriterion("LOCATION_FOUR_PROBABILITY <", value, "locationFourProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFourProbabilityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LOCATION_FOUR_PROBABILITY <=", value, "locationFourProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFourProbabilityIn(List<BigDecimal> values) {
            addCriterion("LOCATION_FOUR_PROBABILITY in", values, "locationFourProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFourProbabilityNotIn(List<BigDecimal> values) {
            addCriterion("LOCATION_FOUR_PROBABILITY not in", values, "locationFourProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFourProbabilityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOCATION_FOUR_PROBABILITY between", value1, value2, "locationFourProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFourProbabilityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOCATION_FOUR_PROBABILITY not between", value1, value2, "locationFourProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFiveProbabilityIsNull() {
            addCriterion("LOCATION_FIVE_PROBABILITY is null");
            return (Criteria) this;
        }

        public Criteria andLocationFiveProbabilityIsNotNull() {
            addCriterion("LOCATION_FIVE_PROBABILITY is not null");
            return (Criteria) this;
        }

        public Criteria andLocationFiveProbabilityEqualTo(BigDecimal value) {
            addCriterion("LOCATION_FIVE_PROBABILITY =", value, "locationFiveProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFiveProbabilityNotEqualTo(BigDecimal value) {
            addCriterion("LOCATION_FIVE_PROBABILITY <>", value, "locationFiveProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFiveProbabilityGreaterThan(BigDecimal value) {
            addCriterion("LOCATION_FIVE_PROBABILITY >", value, "locationFiveProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFiveProbabilityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LOCATION_FIVE_PROBABILITY >=", value, "locationFiveProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFiveProbabilityLessThan(BigDecimal value) {
            addCriterion("LOCATION_FIVE_PROBABILITY <", value, "locationFiveProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFiveProbabilityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LOCATION_FIVE_PROBABILITY <=", value, "locationFiveProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFiveProbabilityIn(List<BigDecimal> values) {
            addCriterion("LOCATION_FIVE_PROBABILITY in", values, "locationFiveProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFiveProbabilityNotIn(List<BigDecimal> values) {
            addCriterion("LOCATION_FIVE_PROBABILITY not in", values, "locationFiveProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFiveProbabilityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOCATION_FIVE_PROBABILITY between", value1, value2, "locationFiveProbability");
            return (Criteria) this;
        }

        public Criteria andLocationFiveProbabilityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOCATION_FIVE_PROBABILITY not between", value1, value2, "locationFiveProbability");
            return (Criteria) this;
        }

        public Criteria andLocationSixProbabilityIsNull() {
            addCriterion("LOCATION_SIX_PROBABILITY is null");
            return (Criteria) this;
        }

        public Criteria andLocationSixProbabilityIsNotNull() {
            addCriterion("LOCATION_SIX_PROBABILITY is not null");
            return (Criteria) this;
        }

        public Criteria andLocationSixProbabilityEqualTo(BigDecimal value) {
            addCriterion("LOCATION_SIX_PROBABILITY =", value, "locationSixProbability");
            return (Criteria) this;
        }

        public Criteria andLocationSixProbabilityNotEqualTo(BigDecimal value) {
            addCriterion("LOCATION_SIX_PROBABILITY <>", value, "locationSixProbability");
            return (Criteria) this;
        }

        public Criteria andLocationSixProbabilityGreaterThan(BigDecimal value) {
            addCriterion("LOCATION_SIX_PROBABILITY >", value, "locationSixProbability");
            return (Criteria) this;
        }

        public Criteria andLocationSixProbabilityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LOCATION_SIX_PROBABILITY >=", value, "locationSixProbability");
            return (Criteria) this;
        }

        public Criteria andLocationSixProbabilityLessThan(BigDecimal value) {
            addCriterion("LOCATION_SIX_PROBABILITY <", value, "locationSixProbability");
            return (Criteria) this;
        }

        public Criteria andLocationSixProbabilityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LOCATION_SIX_PROBABILITY <=", value, "locationSixProbability");
            return (Criteria) this;
        }

        public Criteria andLocationSixProbabilityIn(List<BigDecimal> values) {
            addCriterion("LOCATION_SIX_PROBABILITY in", values, "locationSixProbability");
            return (Criteria) this;
        }

        public Criteria andLocationSixProbabilityNotIn(List<BigDecimal> values) {
            addCriterion("LOCATION_SIX_PROBABILITY not in", values, "locationSixProbability");
            return (Criteria) this;
        }

        public Criteria andLocationSixProbabilityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOCATION_SIX_PROBABILITY between", value1, value2, "locationSixProbability");
            return (Criteria) this;
        }

        public Criteria andLocationSixProbabilityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOCATION_SIX_PROBABILITY not between", value1, value2, "locationSixProbability");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDataIsNull() {
            addCriterion("LAST_UPDATE_DATA is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDataIsNotNull() {
            addCriterion("LAST_UPDATE_DATA is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDataEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATA =", value, "lastUpdateData");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDataNotEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATA <>", value, "lastUpdateData");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDataGreaterThan(Date value) {
            addCriterion("LAST_UPDATE_DATA >", value, "lastUpdateData");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDataGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATA >=", value, "lastUpdateData");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDataLessThan(Date value) {
            addCriterion("LAST_UPDATE_DATA <", value, "lastUpdateData");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDataLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATA <=", value, "lastUpdateData");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDataIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATA in", values, "lastUpdateData");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDataNotIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATA not in", values, "lastUpdateData");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDataBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATA between", value1, value2, "lastUpdateData");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDataNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATA not between", value1, value2, "lastUpdateData");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_location_probability
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_location_probability
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}