package com.fucai.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OddEvenProbability implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column odd_even_probability.ODD_EVEN_ID
     *
     * @mbggenerated
     */
    private Integer oddEvenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column odd_even_probability.ODD_PROBABILITY
     *
     * @mbggenerated
     */
    private BigDecimal oddProbability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column odd_even_probability.EVEN_PROBABILITY
     *
     * @mbggenerated
     */
    private BigDecimal evenProbability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column odd_even_probability.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table odd_even_probability
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column odd_even_probability.ODD_EVEN_ID
     *
     * @return the value of odd_even_probability.ODD_EVEN_ID
     *
     * @mbggenerated
     */
    public Integer getOddEvenId() {
        return oddEvenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column odd_even_probability.ODD_EVEN_ID
     *
     * @param oddEvenId the value for odd_even_probability.ODD_EVEN_ID
     *
     * @mbggenerated
     */
    public void setOddEvenId(Integer oddEvenId) {
        this.oddEvenId = oddEvenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column odd_even_probability.ODD_PROBABILITY
     *
     * @return the value of odd_even_probability.ODD_PROBABILITY
     *
     * @mbggenerated
     */
    public BigDecimal getOddProbability() {
        return oddProbability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column odd_even_probability.ODD_PROBABILITY
     *
     * @param oddProbability the value for odd_even_probability.ODD_PROBABILITY
     *
     * @mbggenerated
     */
    public void setOddProbability(BigDecimal oddProbability) {
        this.oddProbability = oddProbability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column odd_even_probability.EVEN_PROBABILITY
     *
     * @return the value of odd_even_probability.EVEN_PROBABILITY
     *
     * @mbggenerated
     */
    public BigDecimal getEvenProbability() {
        return evenProbability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column odd_even_probability.EVEN_PROBABILITY
     *
     * @param evenProbability the value for odd_even_probability.EVEN_PROBABILITY
     *
     * @mbggenerated
     */
    public void setEvenProbability(BigDecimal evenProbability) {
        this.evenProbability = evenProbability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column odd_even_probability.LAST_UPDATE_DATE
     *
     * @return the value of odd_even_probability.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column odd_even_probability.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for odd_even_probability.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odd_even_probability
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", oddEvenId=").append(oddEvenId);
        sb.append(", oddProbability=").append(oddProbability);
        sb.append(", evenProbability=").append(evenProbability);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}