package com.fucai.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class RedBallProbability implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.BALL_PROBABILITY_ID
     *
     * @mbggenerated
     */
    private Integer ballProbabilityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_ONE
     *
     * @mbggenerated
     */
    private BigDecimal redBallOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_TWO
     *
     * @mbggenerated
     */
    private BigDecimal redBallTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_THREE
     *
     * @mbggenerated
     */
    private BigDecimal redBallThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_FOUR
     *
     * @mbggenerated
     */
    private BigDecimal redBallFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_FIVE
     *
     * @mbggenerated
     */
    private BigDecimal redBallFive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_SIX
     *
     * @mbggenerated
     */
    private BigDecimal redBallSix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_SEVEN
     *
     * @mbggenerated
     */
    private BigDecimal redBallSeven;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_EIGHT
     *
     * @mbggenerated
     */
    private BigDecimal redBallEight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_NINE
     *
     * @mbggenerated
     */
    private BigDecimal redBallNine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_TEN
     *
     * @mbggenerated
     */
    private BigDecimal redBallTen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_ELEVEN
     *
     * @mbggenerated
     */
    private BigDecimal redBallEleven;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_TWELVE
     *
     * @mbggenerated
     */
    private BigDecimal redBallTwelve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_THIRTEEN
     *
     * @mbggenerated
     */
    private BigDecimal redBallThirteen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_FOURTEEN
     *
     * @mbggenerated
     */
    private BigDecimal redBallFourteen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_FIFTEEN
     *
     * @mbggenerated
     */
    private BigDecimal redBallFifteen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_SIXTEEN
     *
     * @mbggenerated
     */
    private BigDecimal redBallSixteen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_SEVENTEEN
     *
     * @mbggenerated
     */
    private BigDecimal redBallSeventeen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_EIGHTEEN
     *
     * @mbggenerated
     */
    private BigDecimal redBallEighteen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_NINETEEN
     *
     * @mbggenerated
     */
    private BigDecimal redBallNineteen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_TWENTY
     *
     * @mbggenerated
     */
    private BigDecimal redBallTwenty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_TWENTY_ONE
     *
     * @mbggenerated
     */
    private BigDecimal redBallTwentyOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_TWENTY_TWO
     *
     * @mbggenerated
     */
    private BigDecimal redBallTwentyTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_TWENTY_THREE
     *
     * @mbggenerated
     */
    private BigDecimal redBallTwentyThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_TWENTY_FOUR
     *
     * @mbggenerated
     */
    private BigDecimal redBallTwentyFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_TWENTY_FIVE
     *
     * @mbggenerated
     */
    private BigDecimal redBallTwentyFive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_TWENTY_SIX
     *
     * @mbggenerated
     */
    private BigDecimal redBallTwentySix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_TWENTY_SEVEN
     *
     * @mbggenerated
     */
    private BigDecimal redBallTwentySeven;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_TWENTY_EIGHT
     *
     * @mbggenerated
     */
    private BigDecimal redBallTwentyEight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_TWENTY_NINE
     *
     * @mbggenerated
     */
    private BigDecimal redBallTwentyNine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_THIRTY
     *
     * @mbggenerated
     */
    private BigDecimal redBallThirty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_THIRTY_ONE
     *
     * @mbggenerated
     */
    private BigDecimal redBallThirtyOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_THIRTY_TWO
     *
     * @mbggenerated
     */
    private BigDecimal redBallThirtyTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.RED_BALL_THIRTY_THREE
     *
     * @mbggenerated
     */
    private BigDecimal redBallThirtyThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_ball_probability.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table red_ball_probability
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.BALL_PROBABILITY_ID
     *
     * @return the value of red_ball_probability.BALL_PROBABILITY_ID
     *
     * @mbggenerated
     */
    public Integer getBallProbabilityId() {
        return ballProbabilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.BALL_PROBABILITY_ID
     *
     * @param ballProbabilityId the value for red_ball_probability.BALL_PROBABILITY_ID
     *
     * @mbggenerated
     */
    public void setBallProbabilityId(Integer ballProbabilityId) {
        this.ballProbabilityId = ballProbabilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_ONE
     *
     * @return the value of red_ball_probability.RED_BALL_ONE
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallOne() {
        return redBallOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_ONE
     *
     * @param redBallOne the value for red_ball_probability.RED_BALL_ONE
     *
     * @mbggenerated
     */
    public void setRedBallOne(BigDecimal redBallOne) {
        this.redBallOne = redBallOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_TWO
     *
     * @return the value of red_ball_probability.RED_BALL_TWO
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallTwo() {
        return redBallTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_TWO
     *
     * @param redBallTwo the value for red_ball_probability.RED_BALL_TWO
     *
     * @mbggenerated
     */
    public void setRedBallTwo(BigDecimal redBallTwo) {
        this.redBallTwo = redBallTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_THREE
     *
     * @return the value of red_ball_probability.RED_BALL_THREE
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallThree() {
        return redBallThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_THREE
     *
     * @param redBallThree the value for red_ball_probability.RED_BALL_THREE
     *
     * @mbggenerated
     */
    public void setRedBallThree(BigDecimal redBallThree) {
        this.redBallThree = redBallThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_FOUR
     *
     * @return the value of red_ball_probability.RED_BALL_FOUR
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallFour() {
        return redBallFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_FOUR
     *
     * @param redBallFour the value for red_ball_probability.RED_BALL_FOUR
     *
     * @mbggenerated
     */
    public void setRedBallFour(BigDecimal redBallFour) {
        this.redBallFour = redBallFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_FIVE
     *
     * @return the value of red_ball_probability.RED_BALL_FIVE
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallFive() {
        return redBallFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_FIVE
     *
     * @param redBallFive the value for red_ball_probability.RED_BALL_FIVE
     *
     * @mbggenerated
     */
    public void setRedBallFive(BigDecimal redBallFive) {
        this.redBallFive = redBallFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_SIX
     *
     * @return the value of red_ball_probability.RED_BALL_SIX
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallSix() {
        return redBallSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_SIX
     *
     * @param redBallSix the value for red_ball_probability.RED_BALL_SIX
     *
     * @mbggenerated
     */
    public void setRedBallSix(BigDecimal redBallSix) {
        this.redBallSix = redBallSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_SEVEN
     *
     * @return the value of red_ball_probability.RED_BALL_SEVEN
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallSeven() {
        return redBallSeven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_SEVEN
     *
     * @param redBallSeven the value for red_ball_probability.RED_BALL_SEVEN
     *
     * @mbggenerated
     */
    public void setRedBallSeven(BigDecimal redBallSeven) {
        this.redBallSeven = redBallSeven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_EIGHT
     *
     * @return the value of red_ball_probability.RED_BALL_EIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallEight() {
        return redBallEight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_EIGHT
     *
     * @param redBallEight the value for red_ball_probability.RED_BALL_EIGHT
     *
     * @mbggenerated
     */
    public void setRedBallEight(BigDecimal redBallEight) {
        this.redBallEight = redBallEight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_NINE
     *
     * @return the value of red_ball_probability.RED_BALL_NINE
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallNine() {
        return redBallNine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_NINE
     *
     * @param redBallNine the value for red_ball_probability.RED_BALL_NINE
     *
     * @mbggenerated
     */
    public void setRedBallNine(BigDecimal redBallNine) {
        this.redBallNine = redBallNine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_TEN
     *
     * @return the value of red_ball_probability.RED_BALL_TEN
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallTen() {
        return redBallTen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_TEN
     *
     * @param redBallTen the value for red_ball_probability.RED_BALL_TEN
     *
     * @mbggenerated
     */
    public void setRedBallTen(BigDecimal redBallTen) {
        this.redBallTen = redBallTen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_ELEVEN
     *
     * @return the value of red_ball_probability.RED_BALL_ELEVEN
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallEleven() {
        return redBallEleven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_ELEVEN
     *
     * @param redBallEleven the value for red_ball_probability.RED_BALL_ELEVEN
     *
     * @mbggenerated
     */
    public void setRedBallEleven(BigDecimal redBallEleven) {
        this.redBallEleven = redBallEleven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_TWELVE
     *
     * @return the value of red_ball_probability.RED_BALL_TWELVE
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallTwelve() {
        return redBallTwelve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_TWELVE
     *
     * @param redBallTwelve the value for red_ball_probability.RED_BALL_TWELVE
     *
     * @mbggenerated
     */
    public void setRedBallTwelve(BigDecimal redBallTwelve) {
        this.redBallTwelve = redBallTwelve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_THIRTEEN
     *
     * @return the value of red_ball_probability.RED_BALL_THIRTEEN
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallThirteen() {
        return redBallThirteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_THIRTEEN
     *
     * @param redBallThirteen the value for red_ball_probability.RED_BALL_THIRTEEN
     *
     * @mbggenerated
     */
    public void setRedBallThirteen(BigDecimal redBallThirteen) {
        this.redBallThirteen = redBallThirteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_FOURTEEN
     *
     * @return the value of red_ball_probability.RED_BALL_FOURTEEN
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallFourteen() {
        return redBallFourteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_FOURTEEN
     *
     * @param redBallFourteen the value for red_ball_probability.RED_BALL_FOURTEEN
     *
     * @mbggenerated
     */
    public void setRedBallFourteen(BigDecimal redBallFourteen) {
        this.redBallFourteen = redBallFourteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_FIFTEEN
     *
     * @return the value of red_ball_probability.RED_BALL_FIFTEEN
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallFifteen() {
        return redBallFifteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_FIFTEEN
     *
     * @param redBallFifteen the value for red_ball_probability.RED_BALL_FIFTEEN
     *
     * @mbggenerated
     */
    public void setRedBallFifteen(BigDecimal redBallFifteen) {
        this.redBallFifteen = redBallFifteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_SIXTEEN
     *
     * @return the value of red_ball_probability.RED_BALL_SIXTEEN
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallSixteen() {
        return redBallSixteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_SIXTEEN
     *
     * @param redBallSixteen the value for red_ball_probability.RED_BALL_SIXTEEN
     *
     * @mbggenerated
     */
    public void setRedBallSixteen(BigDecimal redBallSixteen) {
        this.redBallSixteen = redBallSixteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_SEVENTEEN
     *
     * @return the value of red_ball_probability.RED_BALL_SEVENTEEN
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallSeventeen() {
        return redBallSeventeen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_SEVENTEEN
     *
     * @param redBallSeventeen the value for red_ball_probability.RED_BALL_SEVENTEEN
     *
     * @mbggenerated
     */
    public void setRedBallSeventeen(BigDecimal redBallSeventeen) {
        this.redBallSeventeen = redBallSeventeen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_EIGHTEEN
     *
     * @return the value of red_ball_probability.RED_BALL_EIGHTEEN
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallEighteen() {
        return redBallEighteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_EIGHTEEN
     *
     * @param redBallEighteen the value for red_ball_probability.RED_BALL_EIGHTEEN
     *
     * @mbggenerated
     */
    public void setRedBallEighteen(BigDecimal redBallEighteen) {
        this.redBallEighteen = redBallEighteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_NINETEEN
     *
     * @return the value of red_ball_probability.RED_BALL_NINETEEN
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallNineteen() {
        return redBallNineteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_NINETEEN
     *
     * @param redBallNineteen the value for red_ball_probability.RED_BALL_NINETEEN
     *
     * @mbggenerated
     */
    public void setRedBallNineteen(BigDecimal redBallNineteen) {
        this.redBallNineteen = redBallNineteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_TWENTY
     *
     * @return the value of red_ball_probability.RED_BALL_TWENTY
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallTwenty() {
        return redBallTwenty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_TWENTY
     *
     * @param redBallTwenty the value for red_ball_probability.RED_BALL_TWENTY
     *
     * @mbggenerated
     */
    public void setRedBallTwenty(BigDecimal redBallTwenty) {
        this.redBallTwenty = redBallTwenty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_TWENTY_ONE
     *
     * @return the value of red_ball_probability.RED_BALL_TWENTY_ONE
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallTwentyOne() {
        return redBallTwentyOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_TWENTY_ONE
     *
     * @param redBallTwentyOne the value for red_ball_probability.RED_BALL_TWENTY_ONE
     *
     * @mbggenerated
     */
    public void setRedBallTwentyOne(BigDecimal redBallTwentyOne) {
        this.redBallTwentyOne = redBallTwentyOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_TWENTY_TWO
     *
     * @return the value of red_ball_probability.RED_BALL_TWENTY_TWO
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallTwentyTwo() {
        return redBallTwentyTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_TWENTY_TWO
     *
     * @param redBallTwentyTwo the value for red_ball_probability.RED_BALL_TWENTY_TWO
     *
     * @mbggenerated
     */
    public void setRedBallTwentyTwo(BigDecimal redBallTwentyTwo) {
        this.redBallTwentyTwo = redBallTwentyTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_TWENTY_THREE
     *
     * @return the value of red_ball_probability.RED_BALL_TWENTY_THREE
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallTwentyThree() {
        return redBallTwentyThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_TWENTY_THREE
     *
     * @param redBallTwentyThree the value for red_ball_probability.RED_BALL_TWENTY_THREE
     *
     * @mbggenerated
     */
    public void setRedBallTwentyThree(BigDecimal redBallTwentyThree) {
        this.redBallTwentyThree = redBallTwentyThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_TWENTY_FOUR
     *
     * @return the value of red_ball_probability.RED_BALL_TWENTY_FOUR
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallTwentyFour() {
        return redBallTwentyFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_TWENTY_FOUR
     *
     * @param redBallTwentyFour the value for red_ball_probability.RED_BALL_TWENTY_FOUR
     *
     * @mbggenerated
     */
    public void setRedBallTwentyFour(BigDecimal redBallTwentyFour) {
        this.redBallTwentyFour = redBallTwentyFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_TWENTY_FIVE
     *
     * @return the value of red_ball_probability.RED_BALL_TWENTY_FIVE
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallTwentyFive() {
        return redBallTwentyFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_TWENTY_FIVE
     *
     * @param redBallTwentyFive the value for red_ball_probability.RED_BALL_TWENTY_FIVE
     *
     * @mbggenerated
     */
    public void setRedBallTwentyFive(BigDecimal redBallTwentyFive) {
        this.redBallTwentyFive = redBallTwentyFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_TWENTY_SIX
     *
     * @return the value of red_ball_probability.RED_BALL_TWENTY_SIX
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallTwentySix() {
        return redBallTwentySix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_TWENTY_SIX
     *
     * @param redBallTwentySix the value for red_ball_probability.RED_BALL_TWENTY_SIX
     *
     * @mbggenerated
     */
    public void setRedBallTwentySix(BigDecimal redBallTwentySix) {
        this.redBallTwentySix = redBallTwentySix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_TWENTY_SEVEN
     *
     * @return the value of red_ball_probability.RED_BALL_TWENTY_SEVEN
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallTwentySeven() {
        return redBallTwentySeven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_TWENTY_SEVEN
     *
     * @param redBallTwentySeven the value for red_ball_probability.RED_BALL_TWENTY_SEVEN
     *
     * @mbggenerated
     */
    public void setRedBallTwentySeven(BigDecimal redBallTwentySeven) {
        this.redBallTwentySeven = redBallTwentySeven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_TWENTY_EIGHT
     *
     * @return the value of red_ball_probability.RED_BALL_TWENTY_EIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallTwentyEight() {
        return redBallTwentyEight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_TWENTY_EIGHT
     *
     * @param redBallTwentyEight the value for red_ball_probability.RED_BALL_TWENTY_EIGHT
     *
     * @mbggenerated
     */
    public void setRedBallTwentyEight(BigDecimal redBallTwentyEight) {
        this.redBallTwentyEight = redBallTwentyEight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_TWENTY_NINE
     *
     * @return the value of red_ball_probability.RED_BALL_TWENTY_NINE
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallTwentyNine() {
        return redBallTwentyNine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_TWENTY_NINE
     *
     * @param redBallTwentyNine the value for red_ball_probability.RED_BALL_TWENTY_NINE
     *
     * @mbggenerated
     */
    public void setRedBallTwentyNine(BigDecimal redBallTwentyNine) {
        this.redBallTwentyNine = redBallTwentyNine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_THIRTY
     *
     * @return the value of red_ball_probability.RED_BALL_THIRTY
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallThirty() {
        return redBallThirty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_THIRTY
     *
     * @param redBallThirty the value for red_ball_probability.RED_BALL_THIRTY
     *
     * @mbggenerated
     */
    public void setRedBallThirty(BigDecimal redBallThirty) {
        this.redBallThirty = redBallThirty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_THIRTY_ONE
     *
     * @return the value of red_ball_probability.RED_BALL_THIRTY_ONE
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallThirtyOne() {
        return redBallThirtyOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_THIRTY_ONE
     *
     * @param redBallThirtyOne the value for red_ball_probability.RED_BALL_THIRTY_ONE
     *
     * @mbggenerated
     */
    public void setRedBallThirtyOne(BigDecimal redBallThirtyOne) {
        this.redBallThirtyOne = redBallThirtyOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_THIRTY_TWO
     *
     * @return the value of red_ball_probability.RED_BALL_THIRTY_TWO
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallThirtyTwo() {
        return redBallThirtyTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_THIRTY_TWO
     *
     * @param redBallThirtyTwo the value for red_ball_probability.RED_BALL_THIRTY_TWO
     *
     * @mbggenerated
     */
    public void setRedBallThirtyTwo(BigDecimal redBallThirtyTwo) {
        this.redBallThirtyTwo = redBallThirtyTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.RED_BALL_THIRTY_THREE
     *
     * @return the value of red_ball_probability.RED_BALL_THIRTY_THREE
     *
     * @mbggenerated
     */
    public BigDecimal getRedBallThirtyThree() {
        return redBallThirtyThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.RED_BALL_THIRTY_THREE
     *
     * @param redBallThirtyThree the value for red_ball_probability.RED_BALL_THIRTY_THREE
     *
     * @mbggenerated
     */
    public void setRedBallThirtyThree(BigDecimal redBallThirtyThree) {
        this.redBallThirtyThree = redBallThirtyThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_ball_probability.LAST_UPDATE_DATE
     *
     * @return the value of red_ball_probability.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_ball_probability.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for red_ball_probability.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_ball_probability
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ballProbabilityId=").append(ballProbabilityId);
        sb.append(", redBallOne=").append(redBallOne);
        sb.append(", redBallTwo=").append(redBallTwo);
        sb.append(", redBallThree=").append(redBallThree);
        sb.append(", redBallFour=").append(redBallFour);
        sb.append(", redBallFive=").append(redBallFive);
        sb.append(", redBallSix=").append(redBallSix);
        sb.append(", redBallSeven=").append(redBallSeven);
        sb.append(", redBallEight=").append(redBallEight);
        sb.append(", redBallNine=").append(redBallNine);
        sb.append(", redBallTen=").append(redBallTen);
        sb.append(", redBallEleven=").append(redBallEleven);
        sb.append(", redBallTwelve=").append(redBallTwelve);
        sb.append(", redBallThirteen=").append(redBallThirteen);
        sb.append(", redBallFourteen=").append(redBallFourteen);
        sb.append(", redBallFifteen=").append(redBallFifteen);
        sb.append(", redBallSixteen=").append(redBallSixteen);
        sb.append(", redBallSeventeen=").append(redBallSeventeen);
        sb.append(", redBallEighteen=").append(redBallEighteen);
        sb.append(", redBallNineteen=").append(redBallNineteen);
        sb.append(", redBallTwenty=").append(redBallTwenty);
        sb.append(", redBallTwentyOne=").append(redBallTwentyOne);
        sb.append(", redBallTwentyTwo=").append(redBallTwentyTwo);
        sb.append(", redBallTwentyThree=").append(redBallTwentyThree);
        sb.append(", redBallTwentyFour=").append(redBallTwentyFour);
        sb.append(", redBallTwentyFive=").append(redBallTwentyFive);
        sb.append(", redBallTwentySix=").append(redBallTwentySix);
        sb.append(", redBallTwentySeven=").append(redBallTwentySeven);
        sb.append(", redBallTwentyEight=").append(redBallTwentyEight);
        sb.append(", redBallTwentyNine=").append(redBallTwentyNine);
        sb.append(", redBallThirty=").append(redBallThirty);
        sb.append(", redBallThirtyOne=").append(redBallThirtyOne);
        sb.append(", redBallThirtyTwo=").append(redBallThirtyTwo);
        sb.append(", redBallThirtyThree=").append(redBallThirtyThree);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}