package com.fucai.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SectionProbability implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section_probability.SECTION_ID
     *
     * @mbggenerated
     */
    private Integer sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section_probability.FIRST_SECTION_PROBABILITY
     *
     * @mbggenerated
     */
    private BigDecimal firstSectionProbability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section_probability.SECOND_SECTION_PROBABILITY
     *
     * @mbggenerated
     */
    private BigDecimal secondSectionProbability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section_probability.THIRD__SECTION_PROBABILITY
     *
     * @mbggenerated
     */
    private BigDecimal thirdSectionProbability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section_probability.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table section_probability
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section_probability.SECTION_ID
     *
     * @return the value of section_probability.SECTION_ID
     *
     * @mbggenerated
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section_probability.SECTION_ID
     *
     * @param sectionId the value for section_probability.SECTION_ID
     *
     * @mbggenerated
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section_probability.FIRST_SECTION_PROBABILITY
     *
     * @return the value of section_probability.FIRST_SECTION_PROBABILITY
     *
     * @mbggenerated
     */
    public BigDecimal getFirstSectionProbability() {
        return firstSectionProbability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section_probability.FIRST_SECTION_PROBABILITY
     *
     * @param firstSectionProbability the value for section_probability.FIRST_SECTION_PROBABILITY
     *
     * @mbggenerated
     */
    public void setFirstSectionProbability(BigDecimal firstSectionProbability) {
        this.firstSectionProbability = firstSectionProbability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section_probability.SECOND_SECTION_PROBABILITY
     *
     * @return the value of section_probability.SECOND_SECTION_PROBABILITY
     *
     * @mbggenerated
     */
    public BigDecimal getSecondSectionProbability() {
        return secondSectionProbability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section_probability.SECOND_SECTION_PROBABILITY
     *
     * @param secondSectionProbability the value for section_probability.SECOND_SECTION_PROBABILITY
     *
     * @mbggenerated
     */
    public void setSecondSectionProbability(BigDecimal secondSectionProbability) {
        this.secondSectionProbability = secondSectionProbability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section_probability.THIRD__SECTION_PROBABILITY
     *
     * @return the value of section_probability.THIRD__SECTION_PROBABILITY
     *
     * @mbggenerated
     */
    public BigDecimal getThirdSectionProbability() {
        return thirdSectionProbability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section_probability.THIRD__SECTION_PROBABILITY
     *
     * @param thirdSectionProbability the value for section_probability.THIRD__SECTION_PROBABILITY
     *
     * @mbggenerated
     */
    public void setThirdSectionProbability(BigDecimal thirdSectionProbability) {
        this.thirdSectionProbability = thirdSectionProbability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section_probability.LAST_UPDATE_DATE
     *
     * @return the value of section_probability.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section_probability.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for section_probability.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_probability
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sectionId=").append(sectionId);
        sb.append(", firstSectionProbability=").append(firstSectionProbability);
        sb.append(", secondSectionProbability=").append(secondSectionProbability);
        sb.append(", thirdSectionProbability=").append(thirdSectionProbability);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}