package com.fucai.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ThirtyRedBallProbabilityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    public ThirtyRedBallProbabilityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBallProbabilityIdIsNull() {
            addCriterion("BALL_PROBABILITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdIsNotNull() {
            addCriterion("BALL_PROBABILITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdEqualTo(Integer value) {
            addCriterion("BALL_PROBABILITY_ID =", value, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdNotEqualTo(Integer value) {
            addCriterion("BALL_PROBABILITY_ID <>", value, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdGreaterThan(Integer value) {
            addCriterion("BALL_PROBABILITY_ID >", value, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("BALL_PROBABILITY_ID >=", value, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdLessThan(Integer value) {
            addCriterion("BALL_PROBABILITY_ID <", value, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdLessThanOrEqualTo(Integer value) {
            addCriterion("BALL_PROBABILITY_ID <=", value, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdIn(List<Integer> values) {
            addCriterion("BALL_PROBABILITY_ID in", values, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdNotIn(List<Integer> values) {
            addCriterion("BALL_PROBABILITY_ID not in", values, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdBetween(Integer value1, Integer value2) {
            addCriterion("BALL_PROBABILITY_ID between", value1, value2, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andBallProbabilityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("BALL_PROBABILITY_ID not between", value1, value2, "ballProbabilityId");
            return (Criteria) this;
        }

        public Criteria andRedBallOneIsNull() {
            addCriterion("RED_BALL_ONE is null");
            return (Criteria) this;
        }

        public Criteria andRedBallOneIsNotNull() {
            addCriterion("RED_BALL_ONE is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallOneEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_ONE =", value, "redBallOne");
            return (Criteria) this;
        }

        public Criteria andRedBallOneNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_ONE <>", value, "redBallOne");
            return (Criteria) this;
        }

        public Criteria andRedBallOneGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_ONE >", value, "redBallOne");
            return (Criteria) this;
        }

        public Criteria andRedBallOneGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_ONE >=", value, "redBallOne");
            return (Criteria) this;
        }

        public Criteria andRedBallOneLessThan(BigDecimal value) {
            addCriterion("RED_BALL_ONE <", value, "redBallOne");
            return (Criteria) this;
        }

        public Criteria andRedBallOneLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_ONE <=", value, "redBallOne");
            return (Criteria) this;
        }

        public Criteria andRedBallOneIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_ONE in", values, "redBallOne");
            return (Criteria) this;
        }

        public Criteria andRedBallOneNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_ONE not in", values, "redBallOne");
            return (Criteria) this;
        }

        public Criteria andRedBallOneBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_ONE between", value1, value2, "redBallOne");
            return (Criteria) this;
        }

        public Criteria andRedBallOneNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_ONE not between", value1, value2, "redBallOne");
            return (Criteria) this;
        }

        public Criteria andRedBallTwoIsNull() {
            addCriterion("RED_BALL_TWO is null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwoIsNotNull() {
            addCriterion("RED_BALL_TWO is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwoEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWO =", value, "redBallTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwoNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWO <>", value, "redBallTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwoGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_TWO >", value, "redBallTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWO >=", value, "redBallTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwoLessThan(BigDecimal value) {
            addCriterion("RED_BALL_TWO <", value, "redBallTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWO <=", value, "redBallTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwoIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWO in", values, "redBallTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwoNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWO not in", values, "redBallTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWO between", value1, value2, "redBallTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWO not between", value1, value2, "redBallTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallThreeIsNull() {
            addCriterion("RED_BALL_THREE is null");
            return (Criteria) this;
        }

        public Criteria andRedBallThreeIsNotNull() {
            addCriterion("RED_BALL_THREE is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallThreeEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THREE =", value, "redBallThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThreeNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THREE <>", value, "redBallThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThreeGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_THREE >", value, "redBallThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThreeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THREE >=", value, "redBallThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThreeLessThan(BigDecimal value) {
            addCriterion("RED_BALL_THREE <", value, "redBallThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThreeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THREE <=", value, "redBallThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThreeIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_THREE in", values, "redBallThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThreeNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_THREE not in", values, "redBallThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThreeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_THREE between", value1, value2, "redBallThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThreeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_THREE not between", value1, value2, "redBallThree");
            return (Criteria) this;
        }

        public Criteria andRedBallFourIsNull() {
            addCriterion("RED_BALL_FOUR is null");
            return (Criteria) this;
        }

        public Criteria andRedBallFourIsNotNull() {
            addCriterion("RED_BALL_FOUR is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallFourEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FOUR =", value, "redBallFour");
            return (Criteria) this;
        }

        public Criteria andRedBallFourNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FOUR <>", value, "redBallFour");
            return (Criteria) this;
        }

        public Criteria andRedBallFourGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_FOUR >", value, "redBallFour");
            return (Criteria) this;
        }

        public Criteria andRedBallFourGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FOUR >=", value, "redBallFour");
            return (Criteria) this;
        }

        public Criteria andRedBallFourLessThan(BigDecimal value) {
            addCriterion("RED_BALL_FOUR <", value, "redBallFour");
            return (Criteria) this;
        }

        public Criteria andRedBallFourLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FOUR <=", value, "redBallFour");
            return (Criteria) this;
        }

        public Criteria andRedBallFourIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_FOUR in", values, "redBallFour");
            return (Criteria) this;
        }

        public Criteria andRedBallFourNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_FOUR not in", values, "redBallFour");
            return (Criteria) this;
        }

        public Criteria andRedBallFourBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_FOUR between", value1, value2, "redBallFour");
            return (Criteria) this;
        }

        public Criteria andRedBallFourNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_FOUR not between", value1, value2, "redBallFour");
            return (Criteria) this;
        }

        public Criteria andRedBallFiveIsNull() {
            addCriterion("RED_BALL_FIVE is null");
            return (Criteria) this;
        }

        public Criteria andRedBallFiveIsNotNull() {
            addCriterion("RED_BALL_FIVE is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallFiveEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FIVE =", value, "redBallFive");
            return (Criteria) this;
        }

        public Criteria andRedBallFiveNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FIVE <>", value, "redBallFive");
            return (Criteria) this;
        }

        public Criteria andRedBallFiveGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_FIVE >", value, "redBallFive");
            return (Criteria) this;
        }

        public Criteria andRedBallFiveGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FIVE >=", value, "redBallFive");
            return (Criteria) this;
        }

        public Criteria andRedBallFiveLessThan(BigDecimal value) {
            addCriterion("RED_BALL_FIVE <", value, "redBallFive");
            return (Criteria) this;
        }

        public Criteria andRedBallFiveLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FIVE <=", value, "redBallFive");
            return (Criteria) this;
        }

        public Criteria andRedBallFiveIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_FIVE in", values, "redBallFive");
            return (Criteria) this;
        }

        public Criteria andRedBallFiveNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_FIVE not in", values, "redBallFive");
            return (Criteria) this;
        }

        public Criteria andRedBallFiveBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_FIVE between", value1, value2, "redBallFive");
            return (Criteria) this;
        }

        public Criteria andRedBallFiveNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_FIVE not between", value1, value2, "redBallFive");
            return (Criteria) this;
        }

        public Criteria andRedBallSixIsNull() {
            addCriterion("RED_BALL_SIX is null");
            return (Criteria) this;
        }

        public Criteria andRedBallSixIsNotNull() {
            addCriterion("RED_BALL_SIX is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallSixEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SIX =", value, "redBallSix");
            return (Criteria) this;
        }

        public Criteria andRedBallSixNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SIX <>", value, "redBallSix");
            return (Criteria) this;
        }

        public Criteria andRedBallSixGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_SIX >", value, "redBallSix");
            return (Criteria) this;
        }

        public Criteria andRedBallSixGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SIX >=", value, "redBallSix");
            return (Criteria) this;
        }

        public Criteria andRedBallSixLessThan(BigDecimal value) {
            addCriterion("RED_BALL_SIX <", value, "redBallSix");
            return (Criteria) this;
        }

        public Criteria andRedBallSixLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SIX <=", value, "redBallSix");
            return (Criteria) this;
        }

        public Criteria andRedBallSixIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_SIX in", values, "redBallSix");
            return (Criteria) this;
        }

        public Criteria andRedBallSixNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_SIX not in", values, "redBallSix");
            return (Criteria) this;
        }

        public Criteria andRedBallSixBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_SIX between", value1, value2, "redBallSix");
            return (Criteria) this;
        }

        public Criteria andRedBallSixNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_SIX not between", value1, value2, "redBallSix");
            return (Criteria) this;
        }

        public Criteria andRedBallSevenIsNull() {
            addCriterion("RED_BALL_SEVEN is null");
            return (Criteria) this;
        }

        public Criteria andRedBallSevenIsNotNull() {
            addCriterion("RED_BALL_SEVEN is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallSevenEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SEVEN =", value, "redBallSeven");
            return (Criteria) this;
        }

        public Criteria andRedBallSevenNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SEVEN <>", value, "redBallSeven");
            return (Criteria) this;
        }

        public Criteria andRedBallSevenGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_SEVEN >", value, "redBallSeven");
            return (Criteria) this;
        }

        public Criteria andRedBallSevenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SEVEN >=", value, "redBallSeven");
            return (Criteria) this;
        }

        public Criteria andRedBallSevenLessThan(BigDecimal value) {
            addCriterion("RED_BALL_SEVEN <", value, "redBallSeven");
            return (Criteria) this;
        }

        public Criteria andRedBallSevenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SEVEN <=", value, "redBallSeven");
            return (Criteria) this;
        }

        public Criteria andRedBallSevenIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_SEVEN in", values, "redBallSeven");
            return (Criteria) this;
        }

        public Criteria andRedBallSevenNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_SEVEN not in", values, "redBallSeven");
            return (Criteria) this;
        }

        public Criteria andRedBallSevenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_SEVEN between", value1, value2, "redBallSeven");
            return (Criteria) this;
        }

        public Criteria andRedBallSevenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_SEVEN not between", value1, value2, "redBallSeven");
            return (Criteria) this;
        }

        public Criteria andRedBallEightIsNull() {
            addCriterion("RED_BALL_EIGHT is null");
            return (Criteria) this;
        }

        public Criteria andRedBallEightIsNotNull() {
            addCriterion("RED_BALL_EIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallEightEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_EIGHT =", value, "redBallEight");
            return (Criteria) this;
        }

        public Criteria andRedBallEightNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_EIGHT <>", value, "redBallEight");
            return (Criteria) this;
        }

        public Criteria andRedBallEightGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_EIGHT >", value, "redBallEight");
            return (Criteria) this;
        }

        public Criteria andRedBallEightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_EIGHT >=", value, "redBallEight");
            return (Criteria) this;
        }

        public Criteria andRedBallEightLessThan(BigDecimal value) {
            addCriterion("RED_BALL_EIGHT <", value, "redBallEight");
            return (Criteria) this;
        }

        public Criteria andRedBallEightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_EIGHT <=", value, "redBallEight");
            return (Criteria) this;
        }

        public Criteria andRedBallEightIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_EIGHT in", values, "redBallEight");
            return (Criteria) this;
        }

        public Criteria andRedBallEightNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_EIGHT not in", values, "redBallEight");
            return (Criteria) this;
        }

        public Criteria andRedBallEightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_EIGHT between", value1, value2, "redBallEight");
            return (Criteria) this;
        }

        public Criteria andRedBallEightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_EIGHT not between", value1, value2, "redBallEight");
            return (Criteria) this;
        }

        public Criteria andRedBallNineIsNull() {
            addCriterion("RED_BALL_NINE is null");
            return (Criteria) this;
        }

        public Criteria andRedBallNineIsNotNull() {
            addCriterion("RED_BALL_NINE is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallNineEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_NINE =", value, "redBallNine");
            return (Criteria) this;
        }

        public Criteria andRedBallNineNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_NINE <>", value, "redBallNine");
            return (Criteria) this;
        }

        public Criteria andRedBallNineGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_NINE >", value, "redBallNine");
            return (Criteria) this;
        }

        public Criteria andRedBallNineGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_NINE >=", value, "redBallNine");
            return (Criteria) this;
        }

        public Criteria andRedBallNineLessThan(BigDecimal value) {
            addCriterion("RED_BALL_NINE <", value, "redBallNine");
            return (Criteria) this;
        }

        public Criteria andRedBallNineLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_NINE <=", value, "redBallNine");
            return (Criteria) this;
        }

        public Criteria andRedBallNineIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_NINE in", values, "redBallNine");
            return (Criteria) this;
        }

        public Criteria andRedBallNineNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_NINE not in", values, "redBallNine");
            return (Criteria) this;
        }

        public Criteria andRedBallNineBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_NINE between", value1, value2, "redBallNine");
            return (Criteria) this;
        }

        public Criteria andRedBallNineNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_NINE not between", value1, value2, "redBallNine");
            return (Criteria) this;
        }

        public Criteria andRedBallTenIsNull() {
            addCriterion("RED_BALL_TEN is null");
            return (Criteria) this;
        }

        public Criteria andRedBallTenIsNotNull() {
            addCriterion("RED_BALL_TEN is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallTenEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TEN =", value, "redBallTen");
            return (Criteria) this;
        }

        public Criteria andRedBallTenNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TEN <>", value, "redBallTen");
            return (Criteria) this;
        }

        public Criteria andRedBallTenGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_TEN >", value, "redBallTen");
            return (Criteria) this;
        }

        public Criteria andRedBallTenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TEN >=", value, "redBallTen");
            return (Criteria) this;
        }

        public Criteria andRedBallTenLessThan(BigDecimal value) {
            addCriterion("RED_BALL_TEN <", value, "redBallTen");
            return (Criteria) this;
        }

        public Criteria andRedBallTenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TEN <=", value, "redBallTen");
            return (Criteria) this;
        }

        public Criteria andRedBallTenIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TEN in", values, "redBallTen");
            return (Criteria) this;
        }

        public Criteria andRedBallTenNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TEN not in", values, "redBallTen");
            return (Criteria) this;
        }

        public Criteria andRedBallTenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TEN between", value1, value2, "redBallTen");
            return (Criteria) this;
        }

        public Criteria andRedBallTenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TEN not between", value1, value2, "redBallTen");
            return (Criteria) this;
        }

        public Criteria andRedBallElevenIsNull() {
            addCriterion("RED_BALL_ELEVEN is null");
            return (Criteria) this;
        }

        public Criteria andRedBallElevenIsNotNull() {
            addCriterion("RED_BALL_ELEVEN is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallElevenEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_ELEVEN =", value, "redBallEleven");
            return (Criteria) this;
        }

        public Criteria andRedBallElevenNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_ELEVEN <>", value, "redBallEleven");
            return (Criteria) this;
        }

        public Criteria andRedBallElevenGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_ELEVEN >", value, "redBallEleven");
            return (Criteria) this;
        }

        public Criteria andRedBallElevenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_ELEVEN >=", value, "redBallEleven");
            return (Criteria) this;
        }

        public Criteria andRedBallElevenLessThan(BigDecimal value) {
            addCriterion("RED_BALL_ELEVEN <", value, "redBallEleven");
            return (Criteria) this;
        }

        public Criteria andRedBallElevenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_ELEVEN <=", value, "redBallEleven");
            return (Criteria) this;
        }

        public Criteria andRedBallElevenIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_ELEVEN in", values, "redBallEleven");
            return (Criteria) this;
        }

        public Criteria andRedBallElevenNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_ELEVEN not in", values, "redBallEleven");
            return (Criteria) this;
        }

        public Criteria andRedBallElevenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_ELEVEN between", value1, value2, "redBallEleven");
            return (Criteria) this;
        }

        public Criteria andRedBallElevenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_ELEVEN not between", value1, value2, "redBallEleven");
            return (Criteria) this;
        }

        public Criteria andRedBallTwelveIsNull() {
            addCriterion("RED_BALL_TWELVE is null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwelveIsNotNull() {
            addCriterion("RED_BALL_TWELVE is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwelveEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWELVE =", value, "redBallTwelve");
            return (Criteria) this;
        }

        public Criteria andRedBallTwelveNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWELVE <>", value, "redBallTwelve");
            return (Criteria) this;
        }

        public Criteria andRedBallTwelveGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_TWELVE >", value, "redBallTwelve");
            return (Criteria) this;
        }

        public Criteria andRedBallTwelveGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWELVE >=", value, "redBallTwelve");
            return (Criteria) this;
        }

        public Criteria andRedBallTwelveLessThan(BigDecimal value) {
            addCriterion("RED_BALL_TWELVE <", value, "redBallTwelve");
            return (Criteria) this;
        }

        public Criteria andRedBallTwelveLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWELVE <=", value, "redBallTwelve");
            return (Criteria) this;
        }

        public Criteria andRedBallTwelveIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWELVE in", values, "redBallTwelve");
            return (Criteria) this;
        }

        public Criteria andRedBallTwelveNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWELVE not in", values, "redBallTwelve");
            return (Criteria) this;
        }

        public Criteria andRedBallTwelveBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWELVE between", value1, value2, "redBallTwelve");
            return (Criteria) this;
        }

        public Criteria andRedBallTwelveNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWELVE not between", value1, value2, "redBallTwelve");
            return (Criteria) this;
        }

        public Criteria andRedBallThirteenIsNull() {
            addCriterion("RED_BALL_THIRTEEN is null");
            return (Criteria) this;
        }

        public Criteria andRedBallThirteenIsNotNull() {
            addCriterion("RED_BALL_THIRTEEN is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallThirteenEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTEEN =", value, "redBallThirteen");
            return (Criteria) this;
        }

        public Criteria andRedBallThirteenNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTEEN <>", value, "redBallThirteen");
            return (Criteria) this;
        }

        public Criteria andRedBallThirteenGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_THIRTEEN >", value, "redBallThirteen");
            return (Criteria) this;
        }

        public Criteria andRedBallThirteenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTEEN >=", value, "redBallThirteen");
            return (Criteria) this;
        }

        public Criteria andRedBallThirteenLessThan(BigDecimal value) {
            addCriterion("RED_BALL_THIRTEEN <", value, "redBallThirteen");
            return (Criteria) this;
        }

        public Criteria andRedBallThirteenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTEEN <=", value, "redBallThirteen");
            return (Criteria) this;
        }

        public Criteria andRedBallThirteenIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_THIRTEEN in", values, "redBallThirteen");
            return (Criteria) this;
        }

        public Criteria andRedBallThirteenNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_THIRTEEN not in", values, "redBallThirteen");
            return (Criteria) this;
        }

        public Criteria andRedBallThirteenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_THIRTEEN between", value1, value2, "redBallThirteen");
            return (Criteria) this;
        }

        public Criteria andRedBallThirteenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_THIRTEEN not between", value1, value2, "redBallThirteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFourteenIsNull() {
            addCriterion("RED_BALL_FOURTEEN is null");
            return (Criteria) this;
        }

        public Criteria andRedBallFourteenIsNotNull() {
            addCriterion("RED_BALL_FOURTEEN is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallFourteenEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FOURTEEN =", value, "redBallFourteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFourteenNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FOURTEEN <>", value, "redBallFourteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFourteenGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_FOURTEEN >", value, "redBallFourteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFourteenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FOURTEEN >=", value, "redBallFourteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFourteenLessThan(BigDecimal value) {
            addCriterion("RED_BALL_FOURTEEN <", value, "redBallFourteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFourteenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FOURTEEN <=", value, "redBallFourteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFourteenIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_FOURTEEN in", values, "redBallFourteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFourteenNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_FOURTEEN not in", values, "redBallFourteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFourteenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_FOURTEEN between", value1, value2, "redBallFourteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFourteenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_FOURTEEN not between", value1, value2, "redBallFourteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFifteenIsNull() {
            addCriterion("RED_BALL_FIFTEEN is null");
            return (Criteria) this;
        }

        public Criteria andRedBallFifteenIsNotNull() {
            addCriterion("RED_BALL_FIFTEEN is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallFifteenEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FIFTEEN =", value, "redBallFifteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFifteenNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FIFTEEN <>", value, "redBallFifteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFifteenGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_FIFTEEN >", value, "redBallFifteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFifteenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FIFTEEN >=", value, "redBallFifteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFifteenLessThan(BigDecimal value) {
            addCriterion("RED_BALL_FIFTEEN <", value, "redBallFifteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFifteenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_FIFTEEN <=", value, "redBallFifteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFifteenIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_FIFTEEN in", values, "redBallFifteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFifteenNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_FIFTEEN not in", values, "redBallFifteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFifteenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_FIFTEEN between", value1, value2, "redBallFifteen");
            return (Criteria) this;
        }

        public Criteria andRedBallFifteenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_FIFTEEN not between", value1, value2, "redBallFifteen");
            return (Criteria) this;
        }

        public Criteria andRedBallSixteenIsNull() {
            addCriterion("RED_BALL_SIXTEEN is null");
            return (Criteria) this;
        }

        public Criteria andRedBallSixteenIsNotNull() {
            addCriterion("RED_BALL_SIXTEEN is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallSixteenEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SIXTEEN =", value, "redBallSixteen");
            return (Criteria) this;
        }

        public Criteria andRedBallSixteenNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SIXTEEN <>", value, "redBallSixteen");
            return (Criteria) this;
        }

        public Criteria andRedBallSixteenGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_SIXTEEN >", value, "redBallSixteen");
            return (Criteria) this;
        }

        public Criteria andRedBallSixteenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SIXTEEN >=", value, "redBallSixteen");
            return (Criteria) this;
        }

        public Criteria andRedBallSixteenLessThan(BigDecimal value) {
            addCriterion("RED_BALL_SIXTEEN <", value, "redBallSixteen");
            return (Criteria) this;
        }

        public Criteria andRedBallSixteenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SIXTEEN <=", value, "redBallSixteen");
            return (Criteria) this;
        }

        public Criteria andRedBallSixteenIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_SIXTEEN in", values, "redBallSixteen");
            return (Criteria) this;
        }

        public Criteria andRedBallSixteenNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_SIXTEEN not in", values, "redBallSixteen");
            return (Criteria) this;
        }

        public Criteria andRedBallSixteenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_SIXTEEN between", value1, value2, "redBallSixteen");
            return (Criteria) this;
        }

        public Criteria andRedBallSixteenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_SIXTEEN not between", value1, value2, "redBallSixteen");
            return (Criteria) this;
        }

        public Criteria andRedBallSeventeenIsNull() {
            addCriterion("RED_BALL_SEVENTEEN is null");
            return (Criteria) this;
        }

        public Criteria andRedBallSeventeenIsNotNull() {
            addCriterion("RED_BALL_SEVENTEEN is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallSeventeenEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SEVENTEEN =", value, "redBallSeventeen");
            return (Criteria) this;
        }

        public Criteria andRedBallSeventeenNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SEVENTEEN <>", value, "redBallSeventeen");
            return (Criteria) this;
        }

        public Criteria andRedBallSeventeenGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_SEVENTEEN >", value, "redBallSeventeen");
            return (Criteria) this;
        }

        public Criteria andRedBallSeventeenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SEVENTEEN >=", value, "redBallSeventeen");
            return (Criteria) this;
        }

        public Criteria andRedBallSeventeenLessThan(BigDecimal value) {
            addCriterion("RED_BALL_SEVENTEEN <", value, "redBallSeventeen");
            return (Criteria) this;
        }

        public Criteria andRedBallSeventeenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_SEVENTEEN <=", value, "redBallSeventeen");
            return (Criteria) this;
        }

        public Criteria andRedBallSeventeenIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_SEVENTEEN in", values, "redBallSeventeen");
            return (Criteria) this;
        }

        public Criteria andRedBallSeventeenNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_SEVENTEEN not in", values, "redBallSeventeen");
            return (Criteria) this;
        }

        public Criteria andRedBallSeventeenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_SEVENTEEN between", value1, value2, "redBallSeventeen");
            return (Criteria) this;
        }

        public Criteria andRedBallSeventeenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_SEVENTEEN not between", value1, value2, "redBallSeventeen");
            return (Criteria) this;
        }

        public Criteria andRedBallEighteenIsNull() {
            addCriterion("RED_BALL_EIGHTEEN is null");
            return (Criteria) this;
        }

        public Criteria andRedBallEighteenIsNotNull() {
            addCriterion("RED_BALL_EIGHTEEN is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallEighteenEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_EIGHTEEN =", value, "redBallEighteen");
            return (Criteria) this;
        }

        public Criteria andRedBallEighteenNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_EIGHTEEN <>", value, "redBallEighteen");
            return (Criteria) this;
        }

        public Criteria andRedBallEighteenGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_EIGHTEEN >", value, "redBallEighteen");
            return (Criteria) this;
        }

        public Criteria andRedBallEighteenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_EIGHTEEN >=", value, "redBallEighteen");
            return (Criteria) this;
        }

        public Criteria andRedBallEighteenLessThan(BigDecimal value) {
            addCriterion("RED_BALL_EIGHTEEN <", value, "redBallEighteen");
            return (Criteria) this;
        }

        public Criteria andRedBallEighteenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_EIGHTEEN <=", value, "redBallEighteen");
            return (Criteria) this;
        }

        public Criteria andRedBallEighteenIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_EIGHTEEN in", values, "redBallEighteen");
            return (Criteria) this;
        }

        public Criteria andRedBallEighteenNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_EIGHTEEN not in", values, "redBallEighteen");
            return (Criteria) this;
        }

        public Criteria andRedBallEighteenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_EIGHTEEN between", value1, value2, "redBallEighteen");
            return (Criteria) this;
        }

        public Criteria andRedBallEighteenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_EIGHTEEN not between", value1, value2, "redBallEighteen");
            return (Criteria) this;
        }

        public Criteria andRedBallNineteenIsNull() {
            addCriterion("RED_BALL_NINETEEN is null");
            return (Criteria) this;
        }

        public Criteria andRedBallNineteenIsNotNull() {
            addCriterion("RED_BALL_NINETEEN is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallNineteenEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_NINETEEN =", value, "redBallNineteen");
            return (Criteria) this;
        }

        public Criteria andRedBallNineteenNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_NINETEEN <>", value, "redBallNineteen");
            return (Criteria) this;
        }

        public Criteria andRedBallNineteenGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_NINETEEN >", value, "redBallNineteen");
            return (Criteria) this;
        }

        public Criteria andRedBallNineteenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_NINETEEN >=", value, "redBallNineteen");
            return (Criteria) this;
        }

        public Criteria andRedBallNineteenLessThan(BigDecimal value) {
            addCriterion("RED_BALL_NINETEEN <", value, "redBallNineteen");
            return (Criteria) this;
        }

        public Criteria andRedBallNineteenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_NINETEEN <=", value, "redBallNineteen");
            return (Criteria) this;
        }

        public Criteria andRedBallNineteenIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_NINETEEN in", values, "redBallNineteen");
            return (Criteria) this;
        }

        public Criteria andRedBallNineteenNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_NINETEEN not in", values, "redBallNineteen");
            return (Criteria) this;
        }

        public Criteria andRedBallNineteenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_NINETEEN between", value1, value2, "redBallNineteen");
            return (Criteria) this;
        }

        public Criteria andRedBallNineteenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_NINETEEN not between", value1, value2, "redBallNineteen");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyIsNull() {
            addCriterion("RED_BALL_TWENTY is null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyIsNotNull() {
            addCriterion("RED_BALL_TWENTY is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY =", value, "redBallTwenty");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY <>", value, "redBallTwenty");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY >", value, "redBallTwenty");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY >=", value, "redBallTwenty");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyLessThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY <", value, "redBallTwenty");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY <=", value, "redBallTwenty");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY in", values, "redBallTwenty");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY not in", values, "redBallTwenty");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY between", value1, value2, "redBallTwenty");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY not between", value1, value2, "redBallTwenty");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyOneIsNull() {
            addCriterion("RED_BALL_TWENTY_ONE is null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyOneIsNotNull() {
            addCriterion("RED_BALL_TWENTY_ONE is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyOneEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_ONE =", value, "redBallTwentyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyOneNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_ONE <>", value, "redBallTwentyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyOneGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_ONE >", value, "redBallTwentyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyOneGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_ONE >=", value, "redBallTwentyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyOneLessThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_ONE <", value, "redBallTwentyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyOneLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_ONE <=", value, "redBallTwentyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyOneIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_ONE in", values, "redBallTwentyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyOneNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_ONE not in", values, "redBallTwentyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyOneBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_ONE between", value1, value2, "redBallTwentyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyOneNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_ONE not between", value1, value2, "redBallTwentyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyTwoIsNull() {
            addCriterion("RED_BALL_TWENTY_TWO is null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyTwoIsNotNull() {
            addCriterion("RED_BALL_TWENTY_TWO is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyTwoEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_TWO =", value, "redBallTwentyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyTwoNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_TWO <>", value, "redBallTwentyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyTwoGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_TWO >", value, "redBallTwentyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyTwoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_TWO >=", value, "redBallTwentyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyTwoLessThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_TWO <", value, "redBallTwentyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyTwoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_TWO <=", value, "redBallTwentyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyTwoIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_TWO in", values, "redBallTwentyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyTwoNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_TWO not in", values, "redBallTwentyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyTwoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_TWO between", value1, value2, "redBallTwentyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyTwoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_TWO not between", value1, value2, "redBallTwentyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyThreeIsNull() {
            addCriterion("RED_BALL_TWENTY_THREE is null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyThreeIsNotNull() {
            addCriterion("RED_BALL_TWENTY_THREE is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyThreeEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_THREE =", value, "redBallTwentyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyThreeNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_THREE <>", value, "redBallTwentyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyThreeGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_THREE >", value, "redBallTwentyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyThreeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_THREE >=", value, "redBallTwentyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyThreeLessThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_THREE <", value, "redBallTwentyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyThreeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_THREE <=", value, "redBallTwentyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyThreeIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_THREE in", values, "redBallTwentyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyThreeNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_THREE not in", values, "redBallTwentyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyThreeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_THREE between", value1, value2, "redBallTwentyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyThreeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_THREE not between", value1, value2, "redBallTwentyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFourIsNull() {
            addCriterion("RED_BALL_TWENTY_FOUR is null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFourIsNotNull() {
            addCriterion("RED_BALL_TWENTY_FOUR is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFourEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_FOUR =", value, "redBallTwentyFour");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFourNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_FOUR <>", value, "redBallTwentyFour");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFourGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_FOUR >", value, "redBallTwentyFour");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFourGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_FOUR >=", value, "redBallTwentyFour");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFourLessThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_FOUR <", value, "redBallTwentyFour");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFourLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_FOUR <=", value, "redBallTwentyFour");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFourIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_FOUR in", values, "redBallTwentyFour");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFourNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_FOUR not in", values, "redBallTwentyFour");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFourBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_FOUR between", value1, value2, "redBallTwentyFour");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFourNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_FOUR not between", value1, value2, "redBallTwentyFour");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFiveIsNull() {
            addCriterion("RED_BALL_TWENTY_FIVE is null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFiveIsNotNull() {
            addCriterion("RED_BALL_TWENTY_FIVE is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFiveEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_FIVE =", value, "redBallTwentyFive");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFiveNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_FIVE <>", value, "redBallTwentyFive");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFiveGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_FIVE >", value, "redBallTwentyFive");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFiveGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_FIVE >=", value, "redBallTwentyFive");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFiveLessThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_FIVE <", value, "redBallTwentyFive");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFiveLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_FIVE <=", value, "redBallTwentyFive");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFiveIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_FIVE in", values, "redBallTwentyFive");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFiveNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_FIVE not in", values, "redBallTwentyFive");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFiveBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_FIVE between", value1, value2, "redBallTwentyFive");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyFiveNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_FIVE not between", value1, value2, "redBallTwentyFive");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySixIsNull() {
            addCriterion("RED_BALL_TWENTY_SIX is null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySixIsNotNull() {
            addCriterion("RED_BALL_TWENTY_SIX is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySixEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_SIX =", value, "redBallTwentySix");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySixNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_SIX <>", value, "redBallTwentySix");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySixGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_SIX >", value, "redBallTwentySix");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySixGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_SIX >=", value, "redBallTwentySix");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySixLessThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_SIX <", value, "redBallTwentySix");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySixLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_SIX <=", value, "redBallTwentySix");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySixIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_SIX in", values, "redBallTwentySix");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySixNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_SIX not in", values, "redBallTwentySix");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySixBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_SIX between", value1, value2, "redBallTwentySix");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySixNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_SIX not between", value1, value2, "redBallTwentySix");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySevenIsNull() {
            addCriterion("RED_BALL_TWENTY_SEVEN is null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySevenIsNotNull() {
            addCriterion("RED_BALL_TWENTY_SEVEN is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySevenEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_SEVEN =", value, "redBallTwentySeven");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySevenNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_SEVEN <>", value, "redBallTwentySeven");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySevenGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_SEVEN >", value, "redBallTwentySeven");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySevenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_SEVEN >=", value, "redBallTwentySeven");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySevenLessThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_SEVEN <", value, "redBallTwentySeven");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySevenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_SEVEN <=", value, "redBallTwentySeven");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySevenIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_SEVEN in", values, "redBallTwentySeven");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySevenNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_SEVEN not in", values, "redBallTwentySeven");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySevenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_SEVEN between", value1, value2, "redBallTwentySeven");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentySevenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_SEVEN not between", value1, value2, "redBallTwentySeven");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyEightIsNull() {
            addCriterion("RED_BALL_TWENTY_EIGHT is null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyEightIsNotNull() {
            addCriterion("RED_BALL_TWENTY_EIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyEightEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_EIGHT =", value, "redBallTwentyEight");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyEightNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_EIGHT <>", value, "redBallTwentyEight");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyEightGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_EIGHT >", value, "redBallTwentyEight");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyEightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_EIGHT >=", value, "redBallTwentyEight");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyEightLessThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_EIGHT <", value, "redBallTwentyEight");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyEightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_EIGHT <=", value, "redBallTwentyEight");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyEightIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_EIGHT in", values, "redBallTwentyEight");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyEightNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_EIGHT not in", values, "redBallTwentyEight");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyEightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_EIGHT between", value1, value2, "redBallTwentyEight");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyEightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_EIGHT not between", value1, value2, "redBallTwentyEight");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyNineIsNull() {
            addCriterion("RED_BALL_TWENTY_NINE is null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyNineIsNotNull() {
            addCriterion("RED_BALL_TWENTY_NINE is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyNineEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_NINE =", value, "redBallTwentyNine");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyNineNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_NINE <>", value, "redBallTwentyNine");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyNineGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_NINE >", value, "redBallTwentyNine");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyNineGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_NINE >=", value, "redBallTwentyNine");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyNineLessThan(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_NINE <", value, "redBallTwentyNine");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyNineLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_TWENTY_NINE <=", value, "redBallTwentyNine");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyNineIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_NINE in", values, "redBallTwentyNine");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyNineNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_TWENTY_NINE not in", values, "redBallTwentyNine");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyNineBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_NINE between", value1, value2, "redBallTwentyNine");
            return (Criteria) this;
        }

        public Criteria andRedBallTwentyNineNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_TWENTY_NINE not between", value1, value2, "redBallTwentyNine");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyIsNull() {
            addCriterion("RED_BALL_THIRTY is null");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyIsNotNull() {
            addCriterion("RED_BALL_THIRTY is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY =", value, "redBallThirty");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY <>", value, "redBallThirty");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY >", value, "redBallThirty");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY >=", value, "redBallThirty");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyLessThan(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY <", value, "redBallThirty");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY <=", value, "redBallThirty");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_THIRTY in", values, "redBallThirty");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_THIRTY not in", values, "redBallThirty");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_THIRTY between", value1, value2, "redBallThirty");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_THIRTY not between", value1, value2, "redBallThirty");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyOneIsNull() {
            addCriterion("RED_BALL_THIRTY_ONE is null");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyOneIsNotNull() {
            addCriterion("RED_BALL_THIRTY_ONE is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyOneEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_ONE =", value, "redBallThirtyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyOneNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_ONE <>", value, "redBallThirtyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyOneGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_ONE >", value, "redBallThirtyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyOneGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_ONE >=", value, "redBallThirtyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyOneLessThan(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_ONE <", value, "redBallThirtyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyOneLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_ONE <=", value, "redBallThirtyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyOneIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_THIRTY_ONE in", values, "redBallThirtyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyOneNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_THIRTY_ONE not in", values, "redBallThirtyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyOneBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_THIRTY_ONE between", value1, value2, "redBallThirtyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyOneNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_THIRTY_ONE not between", value1, value2, "redBallThirtyOne");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyTwoIsNull() {
            addCriterion("RED_BALL_THIRTY_TWO is null");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyTwoIsNotNull() {
            addCriterion("RED_BALL_THIRTY_TWO is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyTwoEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_TWO =", value, "redBallThirtyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyTwoNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_TWO <>", value, "redBallThirtyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyTwoGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_TWO >", value, "redBallThirtyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyTwoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_TWO >=", value, "redBallThirtyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyTwoLessThan(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_TWO <", value, "redBallThirtyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyTwoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_TWO <=", value, "redBallThirtyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyTwoIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_THIRTY_TWO in", values, "redBallThirtyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyTwoNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_THIRTY_TWO not in", values, "redBallThirtyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyTwoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_THIRTY_TWO between", value1, value2, "redBallThirtyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyTwoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_THIRTY_TWO not between", value1, value2, "redBallThirtyTwo");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyThreeIsNull() {
            addCriterion("RED_BALL_THIRTY_THREE is null");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyThreeIsNotNull() {
            addCriterion("RED_BALL_THIRTY_THREE is not null");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyThreeEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_THREE =", value, "redBallThirtyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyThreeNotEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_THREE <>", value, "redBallThirtyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyThreeGreaterThan(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_THREE >", value, "redBallThirtyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyThreeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_THREE >=", value, "redBallThirtyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyThreeLessThan(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_THREE <", value, "redBallThirtyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyThreeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RED_BALL_THIRTY_THREE <=", value, "redBallThirtyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyThreeIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_THIRTY_THREE in", values, "redBallThirtyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyThreeNotIn(List<BigDecimal> values) {
            addCriterion("RED_BALL_THIRTY_THREE not in", values, "redBallThirtyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyThreeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_THIRTY_THREE between", value1, value2, "redBallThirtyThree");
            return (Criteria) this;
        }

        public Criteria andRedBallThirtyThreeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RED_BALL_THIRTY_THREE not between", value1, value2, "redBallThirtyThree");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("LAST_UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("LAST_UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(Date value) {
            addCriterion("LAST_UPDATE_DATE >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(Date value) {
            addCriterion("LAST_UPDATE_DATE <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table thirty_red_ball_probability
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}